### ISSUE TITLE
Equality checks fail with generics

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#1033]
The following Rust program:

```rust
use prusti_contracts::*;

pub struct Foo<T>(T);

impl<T: Copy + PartialEq + Eq> Foo<T> {
    #[pure]
    #[ensures(result == (left == right))]
    fn eq(left: T, right: T) -> bool {
        left == right
    }
}
```

fails verification in Prusti with the error:

```
error: [Prusti: verification error] postcondition might not hold.
  --> src/lib.rs:29:15
   |
29 |     #[ensures(result == (left == right))]
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the error originates here
  --> src/lib.rs:30:5
   |
30 | /     fn eq(left: T, right: T) -> bool {
31 | |         left == right
32 | |     }
   | |_____^
```

In the corresponding [Viper program](https://github.com/viperproject/prusti-dev/files/8822976/eq.vpr.txt), it looks like the result variable `_0` is first havoc'd, but then never initialized, causing the assertion to fail:

```
  label l1
  // [mir] _0 = <T as std::cmp::PartialEq>::eq(move _3, move _4) -> [return: bb1, unwind: bb2]
  label l2
  assert true
  exhale acc(_3.val_ref, write) && acc(_4.val_ref, write)
  _0 := builtin$havoc_ref()
  inhale acc(bool(_0), write)

  // --- SNIP ---

  // Assert functional specification of postcondition
  assert (unfolding acc(bool(_0), write) in _0.val_bool == ( // <-- This is the failing assertion
    old[pre](snap$__$TY$__Snap$__TYPARAM__$_T$0$__$(_1))
      == old[pre](snap$__$TY$__Snap$__TYPARAM__$_T$0$__$(_2))
  ))
```

Is this a bug or a current limitation of generics in Prusti? :-)

Thanks!

**Comment by Pointerbender** [comment]
p.s. the problem seems to be rooted in the handling of the assignment terminator, here is the corresponding MIR:

![eq](https://user-images.githubusercontent.com/81013316/171613926-bc4d11a9-dd03-43b2-856b-09b86e17ac36.svg)

**Comment by Pointerbender** [comment]
Some extra information about the call path through the Prusti code base:

When it reaches the `TerminatorKind::Call` of block `bb0` it reaches this statement:

https://github.com/viperproject/prusti-dev/blob/4e478ee4a389996a0f4c514e521c0092e7b926d3/prusti-viper/src/encoder/procedure_encoder.rs#L2362-L2381

where `encode_cmp_function_call` makes the choice whether to use the pure or impure encoding:

https://github.com/viperproject/prusti-dev/blob/4e478ee4a389996a0f4c514e521c0092e7b926d3/prusti-viper/src/encoder/procedure_encoder.rs#L2875-L2932

Surprisingly, it takes the else branch for the impure encoding, this seems off as the `fn eq()` from the example is marked `#[pure]`. It does this, because the if-guard (eventually) checks whether the snapshot supports snapshot equality here:

https://github.com/viperproject/prusti-dev/blob/4e478ee4a389996a0f4c514e521c0092e7b926d3/prusti-viper/src/encoder/snapshot/decls.rs#L92-L99

But in the case of a generic type, the snapshot type is a:

```
Abstract {
    predicate_type: Snapshot(
        SnapshotType {
            label: "__TYPARAM__$_T$0$__",
            arguments: [],
            variant: "",
        },
    ),
    _domain: "Snap$__TYPARAM__$_T$0$__",
    _snap_func: FunctionIdentifier(
        "snap$__$TY$__Snap$__TYPARAM__$_T$0$__$",
    ),
}
```

In this case I think it should be possible to support snapshot equality, because the trait bounds mention `T: Copy + PartialEq + Eq`, which I *think* are sufficient for snapshot equality (because this seems to be okay for the pure function encoder, too, which also uses snapshots based on the criteria that a type is `Copy` - i.e. no interior mutability).

Would it be sound to add a check on `Snapshot::Abstract` that checks whether the `predicate_type` implements `Copy`? If so, what would be the best way to go about this?

**Comment by Pointerbender** [comment]
I may know one way how to do this, I think it's as simple as adding a `| Abstract { ..}` case here:

https://github.com/viperproject/prusti-dev/blob/4e478ee4a389996a0f4c514e521c0092e7b926d3/prusti-viper/src/encoder/snapshot/decls.rs#L92-L99

Informally, I suspect this is sound, too, because:

1) If there is an implementation for the generic type which is not `Copy`, Prusti gives the following nice error message (removing the `#[pure]` or adding the `T: Copy` trait bound fixes the error):

```rust
use prusti_contracts::*;

pub struct Foo<T>(T);

impl<T: PartialEq> Foo<T> {
    #[pure]
    #[ensures(result == (left == right))]
    fn eq(left: T, right: T) -> bool {
        left == right
    }
}
```

```
error: [Prusti: invalid specification] pure function parameters must be Copy
  --> src/lib.rs:38:11
   |
38 |     fn eq(left: T, right: T) -> bool {
   |           ^^^^
```

2) if an impure generic implementation exists and is called from a pure context, then there is also a nice error message:

```rust
use prusti_contracts::*;

pub struct Foo<T>(T);

impl<T: PartialEq> Foo<T> {
    #[ensures(result == (left == right))]
    fn eq(left: T, right: T) -> bool {
        left == right
    }
}

#[pure]
pub fn test() {
    assert!(Foo::eq(0, 0));
}
```

```
error: [Prusti: invalid specification] use of impure function "Foo::<T>::eq" in pure code is not allowed
  --> src/lib.rs:36:13
   |
36 |     assert!(Foo::eq(0, 0));
   |             ^^^^^^^^^^^^^
```

3) So far the Prusti tests are also not complaining yet. If all the tests pass, I will open a PR with the suggested fix and a couple of regression tests :)

**Comment by vakaras** [comment]
> If all the tests pass, I will open a PR with the suggested fix and a couple of regression tests :)

Sounds great! By the way, we should eventually stop assuming that `==` is correct and add a logical equality operator `===` that would be used instead.

**Comment by Pointerbender** [comment]
Just opened PR #1041 with the fix and test cases.

> By the way, we should eventually stop assuming that `==` is correct and add a logical equality operator `===` that would be used instead.

Thanks for the heads up! I noticed the beginnings for that here:

https://github.com/viperproject/prusti-dev/blob/8aa16903d661529fb928935f72b62a99ea9f7f3b/prusti-specs/src/specifications/preparser.rs#L805

Looking forward to that one :)

**Comment by Pointerbender** [comment]
Closing this issue, PR #1041 was merged. :+1:
