### ISSUE TITLE
Consistency error in the server leads to a BrokenPipe

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#104]
A consistency errors in the server is reported as a `BrokenPipe` in the client:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: BrokenPipe, error: StringError("broken pipe") })', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   7: rust_begin_unwind
             at libstd/panicking.rs:337
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: <prusti_server::service::PrustiServerConnection as prusti_common::verification_service::VerificationService>::verify
             at prusti-server/src/service.rs:91
  12: prusti_viper::verifier::Verifier::verify
             at prusti-viper/src/verifier.rs:153
  13: prusti::verifier::verify
             at prusti/src/verifier.rs:51
  14: <prusti::compiler_calls::PrustiCompilerCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
             at prusti/src/compiler_calls.rs:204
  15: rustc::ty::context::tls::with_context
  16: rustc_driver::driver::compile_input::{{closure}}
  17: rustc::ty::context::tls::enter_context
  18: <std::thread::local::LocalKey<T>>::with
  19: rustc::ty::context::TyCtxt::create_and_enter
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler_with_pool
  22: <scoped_tls::ScopedKey<T>>::set
  23: syntax::with_globals
  24: rustc_driver::run_compiler
  25: prusti::prusti_runner::run_prusti
             at prusti/src/prusti_runner.rs:79
  26: prusti_driver::main::{{closure}}
             at prusti/src/driver.rs:76
  27: prusti::driver_utils::run::{{closure}}
             at /home/fpoli/src/prusti/prusti-dev/prusti/src/driver_utils.rs:78
  28: prusti::driver_utils::monitor::{{closure}}
             at /home/fpoli/src/prusti/prusti-dev/prusti/src/driver_utils.rs:29
  29: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /checkout/src/libstd/panic.rs:313
  30: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:310
  31: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  32: std::panicking::try
             at /checkout/src/libstd/panicking.rs:289
  33: std::panic::catch_unwind
             at /checkout/src/libstd/panic.rs:392
  34: rustc_driver::in_rustc_thread
             at /checkout/src/librustc_driver/lib.rs:1545
  35: prusti::driver_utils::monitor
             at /home/fpoli/src/prusti/prusti-dev/prusti/src/driver_utils.rs:29
  36: prusti::driver_utils::run
             at /home/fpoli/src/prusti/prusti-dev/prusti/src/driver_utils.rs:77
  37: prusti_driver::main
             at prusti/src/driver.rs:28
  38: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  39: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  40: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  41: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  42: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  43: main
  44: __libc_start_main
  45: _start
query stack during panic:
end of query stack
```

Cc @juliand665

**Comment by juliand665** [comment]
Ah, so the server is panicking, breaking the pipe. I guess the client should itself panic, but with a more specific message like "The Prusti server encountered an error during verification."?

**Comment by fpoli** [comment]
I'm a bit puzzled because the server should not panic:

https://github.com/viperproject/prusti-dev/blob/a73fdf02e85f0f07c4582d8081d2a8cf6a789da8/viper/src/verifier.rs#L134-L139

And you already handle that in the client:

https://github.com/viperproject/prusti-dev/blob/a73fdf02e85f0f07c4582d8081d2a8cf6a789da8/prusti-viper/src/verifier.rs#L170-L171

Do we have a test that checks that the client receives a `VerificationResult::ConsistencyErrors` in case there is a consistency error in the server?

**Comment by juliand665** [comment]
> Do we have a test that checks that the client receives a `VerificationResult::ConsistencyErrors` in case there is a consistency error in the server?

We do:

https://github.com/viperproject/prusti-dev/blob/a73fdf02e85f0f07c4582d8081d2a8cf6a789da8/viper/tests/invalid_programs.rs#L83-L90

I assumed you were talking about other causes for panics in the server, since I thought this couldn't be the problem…

**Comment by juliand665** [comment]
I've added a simple unit test for this (https://github.com/juliand665/prusti-dev/commit/0beadfcbfdbe5926c847ebd5afca618326a025b7) but couldn't reproduce the issue in that setup. Can you elaborate on your environment, or does that test actually fail on your machine?

**Comment by fpoli** [comment]
Thanks for looking into this. I encounter the panic while running Prusti on crate `h2`. To reproduce:

1. Download this version of the `h2` crate:
    
https://github.com/viperproject/prusti-dev/blob/b96409892848d2c31c8962f2941803b639232b05/evaluation/script/download-top-500.sh#L2554-L2558

2. Take the `Cargo.lock` of `h2` from [here](https://github.com/viperproject/prusti-dev/blob/master/evaluation/crates/locks/423_h2.Cargo.lock) and put it in the `h2` folder.

3. Start a `prusti-server` in a separate terminal

        ~/src/prusti/prusti-dev/target/release/prusti-server --port 12323

4. Run `cargo-prusti` from the folder of `h2`. This correctly reports a consistency error. It may take a few minutes, the first time.

        RUST_BACKTRACE=1 PRUSTI_SKIP_UNSUPPORTED_FUNCTIONS=true PRUSTI_REPORT_SUPPORT_STATUS=false ~/src/prusti/prusti-dev/target/release/cargo-prusti

5. Using the `prusti-server`, run `cargo-prusti` from the folder of `h2`. This does not report a consistency error, but panics.

        PRUSTI_SERVER_ADDRESS="127.0.0.1:12323" RUST_BACKTRACE=1 PRUSTI_SKIP_UNSUPPORTED_FUNCTIONS=true PRUSTI_REPORT_SUPPORT_STATUS=false ~/src/prusti/prusti-dev/target/release/cargo-prusti

**Comment by juliand665** [comment]
Thanks for the directions! I've got the crate downloaded and building, but somehow running cargo-prusti (either from my build dir or from the download on viper.ethz.ch) on it results in just the same output as `cargo check`, no prusti output at all. I actually haven't used cargo-prusti before, so I might be missing something obvious. I had to insert a regular `cargo check` in between your steps 2 and 3 though—maybe that's the issue? It just errored earlier otherwise.

**Comment by fpoli** [comment]
Have you tried deleting `target/` or changing the modification date of a file under `src/`?

**Comment by juliand665** [comment]
That just gets me back to the original problem. Have you seen this kind of error message before?
<img width="682" alt="image" src="https://user-images.githubusercontent.com/827762/87178114-f9565600-c2dc-11ea-851d-cc9c458176ab.png">

**Comment by juliand665** [comment]
Oh, I did indeed miss something obvious: I assumed Prusti would automatically use the correct nightly build of rust, but instead it used stable `cargo`. The easiest fix was to just add the rust-toolchain file to my working directory.

**Comment by juliand665** [comment]
`PRUSTI_SERVER_ADDRESS=MOCK` turned out to be sufficient to reproduce the issue. After taking way too long to think of this, I simply ran that with `RUST_LOG=info` and found the following:
```
 INFO 2020-07-10T23:10:16Z: prusti_viper::verifier: Connecting to Prusti server at [::1]:51008
 WARN 2020-07-10T23:10:16Z: tarpc::protocol: Not sending too-big packet of size 4773702 (max is 2000000)
 WARN 2020-07-10T23:10:16Z: tokio_proto::streaming::multiplex::client: multiplex client dropping with in-flight exchanges
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: BrokenPipe, error: StringError("broken pipe") })', libcore/result.rs:945:5
```
So yeah, it looks like that crate simply results in too much data to send via tarpc. Just one more reason to switch away, as we're doing. 5 MB of data is still quite a lot though; I'm surprised we end up with so much.

**Comment by fpoli** [comment]
> Oh, I did indeed miss something obvious: I assumed Prusti would automatically use the correct nightly build of rust, but instead it used stable `cargo`. The easiest fix was to just add the rust-toolchain file to my working directory.

Oh, yes, I forgot about this. It's #52.

> 

> `PRUSTI_SERVER_ADDRESS=MOCK` turned out to be sufficient to reproduce the issue. After taking way too long to think of this, I simply ran that with `RUST_LOG=info` and found the following:
> 
> ```
>  INFO 2020-07-10T23:10:16Z: prusti_viper::verifier: Connecting to Prusti server at [::1]:51008
>  WARN 2020-07-10T23:10:16Z: tarpc::protocol: Not sending too-big packet of size 4773702 (max is 2000000)
>  WARN 2020-07-10T23:10:16Z: tokio_proto::streaming::multiplex::client: multiplex client dropping with in-flight exchanges
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: BrokenPipe, error: StringError("broken pipe") })', libcore/result.rs:945:5
> ```
> 
> So yeah, it looks like that crate simply results in too much data to send via tarpc. Just one more reason to switch away, as we're doing. 5 MB of data is still quite a lot though; I'm surprised we end up with so much.

Nice catch!

**Comment by fpoli** [comment]
The server now uses `warp` instead of `tarpc`, so this issue should no longer be reproducible.
