### ISSUE TITLE
New filenames break Viper IDE

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#1043]
In commit [882fb31c](https://github.com/viperproject/prusti-dev/commit/882fb31c74bb9bb0dbbff01ec81c23b1c0df8bc7#diff-c97b049428f4a5d2ffe363af30726fc42590cd1d50421d8ab32c4775bc6982c6) there was an update to how filenames are generated. When using `dump_viper_program=true` this now results in filenames with `$$` in them, which breaks Viper IDE on Ubuntu with the error message:

```
> Server: Sending verification request to ViperServer...
> Server: Requesting ViperServer to start new job...
> Server: ViperServer had trouble accepting the POST request: undefined
> Server: It seems that ViperServer's REST API has been changed. Body of response: {
  "msg": "File not found"
}
> Server: ViperServer started new job with ID undefined
ERROR: Server: ViperServer is overwhelmed (ViperServer: File not found). Try again in a few seconds.
> The new state is: Ready
```

Renaming the dumped `.vpr` file to something without `$$` in the name makes the error go away. (Using `::` instead of `$$` used to work okay.)

**Comment by fpoli** [comment]
Thanks for noticing that! I opened https://github.com/viperproject/viper-ide/issues/281, but in the meantime it makes sense to avoid the `$` in Prusti.

**Comment by vakaras** [comment]
I am wondering why it worked for me when I tested this…

**Comment by Pointerbender** [comment]
It works okay through the Viper JNI bridge, it only gives problem in the file names :)

**Comment by fpoli** [comment]
Viper fixed this
