### ISSUE TITLE
Verify code using a set

### ISSUE THREAD

**Issue by ghost** [viperproject/prusti-dev#1085]
For a protocol implementation, I need a set structure. If I understood correctly, FxHash can be used in prusti.

I tried adding fxhash and rustc-hash as dependencies but I get:

```
error[E0432]: unresolved import `rustc_hash`
 --> ../../rusty-raft/src/raft.rs:2:5
  |
2 | use rustc_hash::{FxHashSet as HashSet};
  |     ^^^^^^^^^^ use of undeclared crate or module `rustc_hash`

error: aborting due to 2 previous errors
```

How can I correctly use a set in prusti? My goal is being able to verify properties of this set.

**Comment by JonasAlaif** [comment]
Do you want to add `FxHashSet` while developing the tool Prusti itself, or are you planning to use it in a crate which you want to verify using Prusti? If it is the latter then the error you get is just a normal Rust compiler error telling you that you haven't imported the crate which you are trying to use - see [here](https://stackoverflow.com/questions/48372993/how-can-i-use-a-rustc-crate) how to do that.

**Comment by ghost** [comment]
Thanks for the help.

It is not clear from the fxhash docs if I should use `rustc` or `fxhash` crate, but I have the same error including the dependency like this:

`use fxhash::FxHashSet as HashSet;`

This happens when I try to run `prusti-rustc`, but when I do `cargo build` and `cargo run` it works fine, so I am not sure that it is a dependency problem.
