### ISSUE TITLE
Use of undeclared crate or module `fxhash`

### ISSUE THREAD

**Issue by ghost** [viperproject/prusti-dev#1095]
I am trying to use `fxhash` with prusti. My program builds and run correctly, but when I execute

`./prusti-rustc -Pcheck_overflows=false --edition=2021 ../../rusty-raft/src/raft.rs`

I receive
```
Prusti version: commit 164fa35 2022-03-15 20:32:24 UTC, built on 2022-03-15 21:59:32 UTC
error[E0432]: unresolved import `fxhash`
 --> ../../rusty-raft/src/raft.rs:2:5
  |
2 | use fxhash::FxHashSet as HashSet;
  |     ^^^^^^ use of undeclared crate or module `fxhash`

error: aborting due to previous error
```

I am including the crates like this:

```
use fxhash::FxHashSet as HashSet;
use prusti_contracts::*;
```
and this is my Cargo.toml file

```
[dependencies]
prusti-contracts = { git = "https://github.com/viperproject/prusti-dev.git" }
fxhash = {}
```

**Comment by Aurel300** [comment]
This is because you are using `prusti-rustc`, which is analogous to `rustc`: these binaries don't have a concept of dependencies and will not parse `Cargo.toml`. You should use the `cargo prusti` command instead.

**Comment by pinzaghi** [comment]
Thank you @Aurel300.

How can I use this command? I don't have it in my installation.

**Comment by ghost** [comment]
Thanks @Aurel300.
