### ISSUE TITLE
Issue compiling on M1 Mac 

### ISSUE THREAD

**Issue by dymk** [viperproject/prusti-dev#1108]
I've ran into an issue compiling prusti-dev on an M1 macbook 

Setup:
Downloaded Viper tools 2022.2 and extracted into `viper_tools`: https://www.pm.inf.ethz.ch/research/viper/downloads.html

I'm on prusti-dev ~master (commit hash ` a7fe6a031996705d740349e66c806a748ad9c344`)

My JDK:
```
$> /usr/libexec/java_home -v 11
/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
```

Output from `./x.py build`:

```
error[E0308]: mismatched types
   --> viper/src/silicon_counterexample.rs:226:39
    |
226 |             let value = jni.to_string(value_scala);
    |                             --------- ^^^^^^^^^^^ expected struct `JObject`, found `f64`
    |                             |
    |                             arguments to this function are incorrect
    |
note: associated function defined here
   --> viper/src/jni_utils.rs:118:12
    |
118 |     pub fn to_string(self, object: JObject) -> String {
    |            ^^^^^^^^^ ----  ---------------
```

**Comment by dymk** [comment]
Checking out `fb3c2a4cb6c7f584511dc47e4420dd2c34f16b30` is the last known good commit (or at least, commit that compiles)

**Comment by vakaras** [comment]
You need to use the version of viper tools specified in `viper-toolchain`, which for the master is `v-2022-07-21-0735`. You should be able to use `./x.py setup` to download it.

**Comment by vakaras** [comment]
> Downloaded Viper tools 2022.2

This is the last stable release of Viper. Prusti uses nightly releases.

**Comment by dymk** [comment]
Thank you! I've got a "hello world" checking on an M1 mac, now.
