### ISSUE TITLE
Use a parser library to parse specifications.

### ISSUE THREAD

**Issue by frececroka** [viperproject/prusti-dev#111]
At the moment, specifications are parsed manually in `prusti-interface/src/parser.rs`. This involves regular expressions, iterating over characters, counting and matching parentheses, etc. I believe it would make modifications of the specification language easier if we use a parser library (for example [Pest](https://pest.rs/)) to turn specification strings into parse trees.

For example, I'm working on extending the syntax for pledges right now. With Pest, I could define the syntax like this (not complete):

```
pledge = { "pledge" ~ "(" ~ pledge_body ~ ")" }

pledge_body = {
    pledge_term ~ "==" ~ pledge_body |
    pledge_term ~ "&&" ~ pledge_body |
    pledge_term ~ "||" ~ pledge_body |
    pledge_term
}

pledge_term = {
    "(" ~ pledge_term ~ ")" |
    after_unblocked |
    before_expiry |
    expression
}

after_unblocked = {
    "after_unblocked" ~ "(" ~ expression ~ ")"
}

before_expiry = {
    "before_expiry" ~ "(" ~ expression ~ ")"
}

expression = { ASCII_ALPHANUMERIC+ }

WHITESPACE = _{ " " }
```

And then a string like `pledge(after_unblocked(a) == before_expiry(b))` is parsed into the following tree:

```
- pledge > pledge_body
  - pledge_body_basic > after_unblocked > expression: "a"
  - pledge_body > pledge_body_basic > before_expiry > expression: "b"
```

There's an [online editor](https://pest.rs/#editor) to play with language definitions.

Of course this is a change that requires quite a bit of work without giving an immediate benefit, so maybe it's something for less busy times :). However, it would afford us much more flexibility in the definition of the specification language and probably also make bug like https://github.com/viperproject/prusti-dev/issues/24 less likely.

**Comment by frececroka** [comment]
After diving further into the parsing I see that expressions like `after_unblocked(a) == before_expiry(b)` are parsed by Rust directly, but for things like conjunctions, forall, etc. it could still make sense to make use of something like Pest.

**Comment by fpoli** [comment]
@vakaras and @karlosss are working on this in the rustc-update branch.

**Comment by karlosss** [comment]
...and we are using a library so that the parsing is actually reliable.

**Comment by frececroka** [comment]
Ah great news! I guess I'm psychic :) Which library are you using?

**Comment by karlosss** [comment]
The specifications are no longer strings, rather we make use of Rust macros and parse using [`syn`](https://docs.rs/syn/1.0.34/syn/index.html). You can see an example of the new specs in use [here](https://github.com/viperproject/prusti-dev/blob/rustc-update/prusti/tests/pass/parse/composite.rs) and the parsing itself is implemented [here](https://github.com/viperproject/prusti-dev/blob/rustc-update/prusti-specs/src/specifications/preparser.rs#L274). Unlike the previous parser, this one actually has even some minimal documentation.

**Comment by frececroka** [comment]
Wow that looks very nice. Using closure syntax for quantifiers is especially neat.
