### ISSUE TITLE
FxHashSet: Postcondition might not hold

### ISSUE THREAD

**Issue by ghost** [viperproject/prusti-dev#1112]
I am trying to understand why this postcondtion cannot be proved:

```
use fxhash::FxHashSet;
use prusti_contracts::*;

#[extern_spec]
impl<V> FxHashSet<V> {
    #[pure]
    pub fn len<S>(&self) -> usize;
}

#[ensures(old(someset.len()) <= someset.len())]
pub fn set_function(someset: &mut FxHashSet::<usize>){
    someset.insert(1);
}
```

when I execute `cargo-prusti` the output is:

```
error: [Prusti: verification error] postcondition might not hold.
  --> src/lib.rs:10:11
   |
10 | #[ensures(old(someset.len()) <= someset.len())]
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the error originates here
  --> src/lib.rs:11:1
   |
11 | / pub fn set_function(someset: &mut FxHashSet::<usize>){
12 | |     someset.insert(1);
13 | | }
   | |_^
note: counterexample for "someset"
        initial value: ref(HashSet {
            base: HashSet {
                map: ?,
            },
        })
        final value:   ref(HashSet {
            base: HashSet {
                map: ?,
            },
        })
  --> src/lib.rs:11:21
   |
11 | pub fn set_function(someset: &mut FxHashSet::<usize>){
   |                     ^^^^^^^

error: could not compile `test-hash` due to previous error
```

Prusti version: commit a7fe6a0 2022-07-29 19:46:54 UTC, built on 2022-07-29 23:01:29 UTC
rustc 1.64.0-nightly (c2f428d2f 2022-07-14)

**Comment by Aurel300** [comment]
The `insert` method has no contract. Since it takes a mutable reference (`&mut self`), that means it could, in principle, modify the given set arbitrarily. In other words, it havocs (assigns an arbitrary value) `someset.len()`.

**Comment by ghost** [comment]
That makes sense. If I understand correctly, there is support for the `FxHash` crate but that doesn't means that it has any postcondition associated. I should add an `extern_spec` for `insert()`, right?

**Comment by Aurel300** [comment]
Yes, there are no contracts automatically provided for any crates (yet). Adding an extern spec for `insert` will help, yes.
