### ISSUE TITLE
Thread 'rustc' paniced

### ISSUE THREAD

**Issue by liuw1** [viperproject/prusti-dev#1127]
thread 'rustc' panicked at 'Error while analyzing function at td-uefi-pi/src/hob.rs:677:1: 679:2 (#0): Unsupported statement at bb0[1]: asm!("lfence", options((empty))) -> bb1', prusti-interface/src/environment/mir_analyses/initialization.rs:76:13

Scan project:
https://github.com/confidential-containers/td-shim
crate: td-uefi-pi

**Comment by liuw1** [comment]
It seems prusti doesn't support macro asm!?

**Comment by vakaras** [comment]
Yes, assembly is not supported.

**Comment by liuw1** [comment]
@vakaras Thank you! BTW, is there any methods to skip the panic?

**Comment by vakaras** [comment]
Marking function with `#[trusted]` should help.

**Comment by liuw1** [comment]
@vakaras Thanks a lot! it works, I copied some crates into my project and then marked function with #[trusted].
