### ISSUE TITLE
Prusti-assistant verification exits with "an unexpected error"

### ISSUE THREAD

**Issue by danielrab** [viperproject/prusti-dev#1139]
I tried installing the prusti-assistant VS Code extension. It added the "Verify with prusti" button, but when I try to click it, it terminates with an error, without highlighting any problems. I do not exclude the possibility that I installed something wrong, but I think I followed the instructions well. Here's the log:
```
Run verification on c:\Users\s17b1\Desktop\rust\prusti_test\src\main.rs...
Preparing verification run #3.
Killing 0 processes.
Run command 'c:\Users\s17b1\AppData\Roaming\Code\User\globalStorage\viper-admin.prusti-assistant\prustiTools\LatestRelease\prusti\cargo-prusti.exe --message-format=json'
Spawned PID: 18228
Output from 'c:\Users\s17b1\AppData\Roaming\Code\User\globalStorage\viper-admin.prusti-assistant\prustiTools\LatestRelease\prusti\cargo-prusti.exe --message-format=json' (0.1s):
┌──── Begin stdout ────┐
{"reason":"build-finished","success":false}

└──── End stdout ──────┘
┌──── Begin stderr ────┐
    Checking prusti_test v0.1.0 (C:\Users\s17b1\Desktop\rust\prusti_test)
[2022-08-22T15:16:32Z INFO  prusti_driver] Prusti version: commit 4dfd34d 2021-11-22 16:35:31 UTC, built on 2021-11-22 16:46:17 UTC
error: unknown `--json` option `future-incompat`

error: could not compile `prusti_test`

└──── End stderr ──────┘
Exit code 101, signal null.
The verification failed, but there are no errors to report.
Prusti encountered an unexpected error. We would appreciate a [bug report](https://github.com/viperproject/prusti-dev/issues/new). See the log (View -> Output -> Prusti Assistant) for more details.
```

**Comment by JonasAlaif** [comment]
Hmm I can't seem to be able to reproduce the problem with just making a `prusti_test` crate myself with prusti-assistant, neither on the LatestDev or LatestRelease version. Could you attach a copy of the crate you are trying to verify so that I can try it specifically with that?

**Comment by danielrab** [comment]
it literally contains just `fn main() {}` in src/main.rs and
```[package]
name = "prusti_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```
in cargo.toml
It's probably some problem somewhere else in my setup. Hoped you encountered something like this, but if no, I'll try to figure it out and report if I manage to find the reason. I did manage to make the command line version work though.

**Comment by danielrab** [comment]
well, I tried on a new machine.
Both my main machine and that laptop run windows 11.
- installed rust
- downloaded openjdk and added it to PATH
- installed VS Code
- installed Rust-analyzer extesnion
- installed Prsuti-assistant extension
- used "cargo new prusti_test"
- opened the crate in VS Code
- waited until Prusti verified dependencies
- got the same result

**Comment by Aurel300** [comment]
The actual error in your output is "unknown `--json` option `future-incompat`", which [seems](https://stackoverflow.com/questions/72110443/rust-build-error-unknown-json-option-future-incompat) to be a problem with Rust versions.

When you say "installed rust", do you mean you used [`rustup`](https://rustup.rs/)? The file [`rust-toolchain`](https://github.com/viperproject/prusti-dev/blob/0686adc3d211e3b5a76e058437ed5fe5c0d16a8e/rust-toolchain#L2) in our repository version-locks Prusti to a particular nightly version of the compiler. @fpoli does the IDE extension do anything with the installed Rust version? Can `cargo-prusti` be compiled with a different version than the current compiler version?

@danielrab If you indeed used `rustup`, can you try to use the toolchain `nightly-2022-08-01` and switch to the "nighly" build channel in Prusti Assistant preferences?

**Comment by danielrab** [comment]
Thank you very much, after I switched `Prusti Assistant` to `LatestDev` in the prefererences made it work.
Didn't even need to switch rustup toolchain.
And yes, by installing Rust I meant installing rustup and running it.

**Comment by danielrab** [comment]
Well, I guess the issue is resolved, so I'll close it.
