### ISSUE TITLE
Better instructions for installing Java on macOS (arm64)

### ISSUE THREAD

**Issue by djc** [viperproject/prusti-dev#1196]
I would like to use Prusti and tried installing the VS Code extension. At first I found it confusing that it seemed to get stuck on "Checking requirements". After I found the output pane for Prusti Assistant I figured out that it was unable to find Java. I first checked the README on GitHub, but that didn't help:

* There are installation instructions toward the bottom, but they don't talk about the Java requirement at all
* Neither do the installation instructions in the user guide (https://viperproject.github.io/prusti-dev/user-guide/install.html)
* The precompiled binaries mentioned there do not include a JVM
* As such, the "For more detailed instructions, refer to the guides linked above." didn't ring true to me

I started looking for a good way to install Java using DuckDuckGo, this led me to https://stackoverflow.com/questions/64788005/java-jdk-for-the-apple-silicon-chips. From there, I used Homebrew to install openjdk (openjdk--19.arm64_monterey.bottle.tar.gz).

At some point I found somewhere that specifically mentioned the VS Code extension description, and read the instructions (in particular, the Troubleshooting part) in more detail.

(The instructions link to https://jdk.java.net/15/, but that just says "JDK 15 has been superseded. Please visit [jdk.java.net](https://jdk.java.net/) for the current version.".)

After installing the OpenJDK from Homebrew, Prusti still couldn't find the JVM. I used the Extension configuration path since I couldn't think of an easy way to set the environment variable that would trivially be picked up by VS Code. Initially I added the `/bin` path (since that's what Homebrew recommends setting as the path), but after another that it was still unable to find it I noticed the duplicate `/bin` in the path and managed to fix that. After that, I got to the next problem:

```
[stderr] dyld[1139]: Library not loaded: '@rpath/libjli.dylib'
  Referenced from: '/Users/djc/Library/Application Support/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-server-driver'
  Reason: tried: '/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/lib/libjli.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
```

I proceeded to download https://download.java.net/java/GA/jdk19/877d6127e982470ba2a7faa31cc93d04/36/GPL/openjdk-19_macos-x64_bin.tar.gz, unpacking it and managed to find Java home-like contents in `jdk-19.jdk/Contents/Home`. This got Prusti Assistant ready for verification, just for it to fail again as soon as I tried to verify some code:

```
process didn't exit successfully: `/Users/djc/Library/Application Support/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-rustc rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 255)
  --- stderr
  dyld[1965]: Library not loaded: '@rpath/librustc_driver-88b66bfaeeb90970.dylib'
    Referenced from: '/Users/djc/Library/Application Support/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-driver'
    Reason: tried: '/Users/djc/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/djc/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/bin/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/djc/tmp/jdk-19.jdk/Contents/Home/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/djc/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/Users/djc/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/usr/local/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file), '/usr/lib/librustc_driver-88b66bfaeeb90970.dylib' (no such file)
```

(I do have ~/.rustup/toolchains/nightly-2022-09-18-aarch64-apple-darwin/lib/librustc_driver-253cb49ee5665ce9.dylib -- I can't think of a reason that it's looking for a different hash here.)

FWIW, I am a pretty experienced Rust user and I know my way about Unix in general and macOS in particular -- although I have pretty much no experience with the Java ecosystem. I think the first-run/installation experience and documentation need a lot of work if you'd like for Prusti to be more widely used...

**Comment by fpoli** [comment]
Wow, what a nightmare! Thanks for reporting that.

My summary:
1. Installation instructions and requirements are spread over various places: this repo's readme, user/dev guides, and the more complete but less visible readme of [Prusti Assistant](https://github.com/viperproject/prusti-assistant). We find a way to keep them in sync, or just have all instructions in one place.
2. At the moment, we are not releasing nor testing Prusti for macOS running on M1. So, M1 incorrectly gets the binaries for Intel and we were not aware of that. We are tracking this in https://github.com/viperproject/prusti-dev/issues/1193.
3. Prusti Assistant's prerequirite checks seem to be not working on M1.

**Comment by djc** [comment]
That's a pretty good summary. I would probably recommend to centralize all the documentation in the user guide, and provide a link from the extension description to that. In the README, I would recommend renaming "Using Prusti" to make it clear that it's talking about installation instructions, and move that before the "Quick Example" section (or also move that section into the user guide, and potentially provide a separate link to the installation instructions page in the user guide from the user guide bullet in the "Documentation" section.

Is the final error message also due to the ARM vs Intel difference?

**Comment by fpoli** [comment]
> Is the final error message also due to the ARM vs Intel difference?

I suspect so, but I don't have an M1 to be 100% sure. My explanation is that the binaries precompiled for Intel (downloaded by the IDE from the releases of this repo) depend on dynamic libraries whose hash only matches Intel rust installations, which you don't have.

What should work on M1 is to compile Prusti from source code (`./x.py build`), prepare a package (`./x.py package build new/package/path`; not documented :-/), go in the settings of Prusti Assistant and make it use the newly created package (choosing the "Local" channel and then filling the local path field).

**Comment by djc** [comment]
So after copying the Viper tools `./x.py build` works, but `./x.py package` fails:

```
djc-2021 master prusti-dev $ ./x.py package build foodaddle
INFO: Preparing a build-mode Prusti package in 'foodaddle'.
WARNING: The destination folder 'foodaddle' is not empty.
INFO: Copying 'rust-toolchain' to 'foodaddle/./rust-toolchain'...
INFO: Copying 'viper_tools' to 'foodaddle/./viper_tools'...
INFO: Copied 2 paths to the package folder
ERROR: The number of copied paths is too low.
```

**Comment by fpoli** [comment]
That's odd, we periodically run `./x.py package` on macOS without issues when creating the releases: https://github.com/viperproject/prusti-dev/blob/5ed30dce418c5dc61d6ef46b4eacdb48d4c9fb84/.github/workflows/deploy.yml#L46-L47

I'm adding some debug: https://github.com/viperproject/prusti-dev/pull/1208

**Comment by fpoli** [comment]
This issue should be covered by https://github.com/viperproject/prusti-dev/issues/1236, https://github.com/viperproject/prusti-dev/issues/1193, https://github.com/viperproject/prusti-assistant/issues/191.
