### ISSUE TITLE
Internal error when mutating in 'loop' with conditional 'break'

### ISSUE THREAD

**Issue by burjui** [viperproject/prusti-dev#1205]
```rust
fn main() {
    let mut i = 0;
    loop {
        i += 1;
        if i == 10 {
            break;
        }
    }
}
```
Details: cannot generate fold-unfold Viper statements. The required permission Pred(_3.tuple_0, write) cannot be obtained.

The same happens if you replace `i == 10` with `true`.

**Comment by fpoli** [comment]
I believe this is an instance of https://github.com/viperproject/prusti-dev/issues/389

**Comment by fpoli** [comment]
A temporary workaround is to manually place a dummy loop invariant at the beginning of the method.

```rust
use prusti_contracts::*;

fn main() {
    let mut i = 0;
    loop {
    	body_invariant!(true);
        i += 1;
        if i == 10 {
            break;
        }
    }
}
```

Thank you for the report. I'm closing this because I added the examples to #389.
