### ISSUE TITLE
Z3's regression on bubble sort (z3 4.8.8 to z3 4.8.10)

### ISSUE THREAD

**Issue by safinaskar** [viperproject/prusti-dev#1245]
I'm continuing my attempts to verify bubble sort. Here is version I use this time:
```rust
extern crate prusti_contracts;
use prusti_contracts::*;

fn sort(a: &mut [i32]) {
    if a.len() == 0 {
        return;
    }
    let mut i = 0;
    while i < a.len() - 1 {
        body_invariant!(true);
        body_invariant!(i + 1 <= a.len());
        body_invariant!(a.len() >= 1);
        body_invariant!(i > 0 ==> forall(|k: usize|k < a.len() - i ==> a[k] <= a[a.len() - i]));
        prusti_assume!(forall(|k: usize|(a.len() - i - 1 <= k && k < a.len() - 1) ==> a[k] <= a[k + 1]));
        {
            let mut j = 0;
            while j < a.len() - i - 1 {
                body_invariant!(true);
                body_invariant!(j < a.len());
                body_invariant!(forall(|k: usize|(k < j) ==> (a[k] <= a[j])));
                body_invariant!(forall(|k: usize|(a.len() - i <= k && k < a.len() - 1) ==> a[k] <= a[k + 1]));
                if a[j] > a[j + 1] {
                    let sw = a[j];
                    a[j] = a[j + 1];
                    a[j + 1] = sw;
                }
                j += 1;
            }
        }
        i += 1;
    }
}

fn main(){ }
```
(This version slightly differs from version present in https://github.com/viperproject/prusti-dev/issues/1243 ). I use prusti dcb86a5caf6e5c6d5d511735e175b93a44d70322 .

I found a regression in z3. I build z3 from its sources using gcc. z3 version 4.8.7 works correctly with this example. `cargo prusti` finishes in 2m 21s. But when I use z3 4.11.2, `cargo prusti` works for more than 10 minutes (and then I terminate the command).

I found this thread: https://twitter.com/RanjitJhala/status/1391486845435871233 , so I decided to test mentioned versions. Results: 4.8.8 works nearly same time as 4.8.7. And 4.8.10 again works more that 10 minutes.

I did `git bisect` and found first bad commit: https://github.com/Z3Prover/z3/commit/e955bd09e52d3277555af3e2f8a0933bfaa2f36a . My tests on this commit show that `cargo prusti` works for more than 35 mins (and then I abort computation). I. e. I don't even know whether the computation will actually terminate, i. e. I don't know whether this is performance regression or correctness regression.

All these tests were performed on AWS EC2 m5zn.6xlarge

**Comment by fpoli** [comment]
To properly evaluate regressions in Z3 one should also randomize the seed; see my comment [here](https://github.com/viperproject/prusti-dev/issues/1243#issuecomment-1323435522).

If there a big regression in Z3 that affects many programs, I think we should report it [Viper's repo](https://github.com/viperproject/viper-ide). When we change the version of Z3 that is released with Viper we already check for regressions. This is why don't explicitly choose a version of Z3 in Prusti.

**Comment by safinaskar** [comment]
I enabled that `Prusti.toml` option. I tested this Rust code (from this bug report) on z3 4.8.6 (from that viper zip archive). Result: completes successfully in 251.78. Then I tested with z3 4.11.2 I built using gcc. And `cargo prusti` failed after 763.16 s with this message:
```text
warning: function `sort` is never used
 --> src/main.rs:4:4
  |
4 | fn sort(a: &mut [i32]) {
  |    ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

error: [Prusti: verification error] assertion might fail with "attempt to subtract with overflow"
  --> src/main.rs:17:23
   |
17 |             while j < a.len() - i - 1 {
   |                       ^^^^^^^^^^^

warning: `good-example` (bin "good-example") generated 1 warning
error: could not compile `good-example` due to previous error; 1 warning emitted
```

So, yes, I still see regression. And it seems new z3 versions cannot check this file at all

**Comment by safinaskar** [comment]
As I said before, https://github.com/Z3Prover/z3/commit/e955bd09e52d3277555af3e2f8a0933bfaa2f36a is the first bad commit. I tested it again, now with Prusti.toml. Result: `cargo prusti` failed after 430.11 s with error `assertion might fail with "attempt to subtract with overflow"`.

Previous commit (i. e. https://github.com/Z3Prover/z3/commit/3c9ada54b64e5516e0cf869c5de7881686df8fd0 ) still works OK. Finished successfully in 143.40 s

**Comment by fpoli** [comment]
Thanks! I opened https://github.com/viperproject/silicon/issues/664. Could you please attach to this issue the dump of the Viper programs?

To generate the dump, add the following and rerun Prusti. The dump will appear in `log/viper_program/*.vpr`
```
# Prusti.toml
dump_viper_program = true
```

**Comment by fpoli** [comment]
(I renamed the title because getting more errors is something that we call *incompleteness*, not *correctness*.)

**Comment by safinaskar** [comment]
I reduced test case:
```rust
extern crate prusti_contracts;
use prusti_contracts::*;

fn sort(a: &mut [i32]) {
    if a.len() == 0 {
        return;
    }
    let mut i = 0;
    while i < a.len() - 1 {
        body_invariant!(true);
        body_invariant!(i + 1 <= a.len());
        body_invariant!(a.len() >= 1);
        prusti_assume!(forall(|k: usize|(a.len() - i - 1 <= k && k < a.len() - 1) ==> a[k] <= a[k + 1]));
        {
            let mut j = 0;
            while j < 5 {
                body_invariant!(true);
                body_invariant!(forall(|k: usize|(a.len() - i <= k && k < a.len() - 1) ==> a[k] <= a[k + 1]));
                j += 1;
            }
        }
        i += 1;
    }
}

fn main(){ }
```
This code works on https://github.com/Z3Prover/z3/commit/3c9ada54b64e5516e0cf869c5de7881686df8fd0 and doesn't work on https://github.com/Z3Prover/z3/commit/e955bd09e52d3277555af3e2f8a0933bfaa2f36a .

Is dump still needed? (Or there is no sense in dump because of https://github.com/viperproject/silicon/issues/664#issuecomment-1324811845 ?)

**Comment by fpoli** [comment]
No longer needed, thanks. I'll close this issue since the regressions with recent Z3 versions are known and checked in Viper.
