### ISSUE TITLE
Prusti Server stop working VS

### ISSUE THREAD

**Issue by miteshjain** [viperproject/prusti-dev#1257]
<img width="1512" alt="Screen Shot 2022-12-02 at 6 50 19 AM" src="https://user-images.githubusercontent.com/1581196/205193199-3fc3d0cc-d5e1-4ef5-8fa6-6a8c2ad1b58e.png">

**Comment by fpoli** [comment]
Thank you for the report. Unfortunately, there is not enough information to reproduce the issue. If you can describe the steps to reproduce that error, please open an issue on https://github.com/viperproject/prusti-assistant/issues and attach the log.
