### ISSUE TITLE
Unsupported constant type `Ref(...)`

### ISSUE THREAD

**Issue by Patrick-6** [viperproject/prusti-dev#1268]
Logical Equality currently does not work for enums:
```
use prusti_contracts::*;

pub enum TestEnum {
    Nil,
}

#[ensures(TestEnum::Nil === TestEnum::Nil)]
fn test() {}
```
Error on `=== TestEnum::Nil`:
```
[Prusti: unsupported feature]
unsupported constant type Ref(ReErased, bug::unsupported_enum_equality::TestEnum, Not)
```

**Comment by Aurel300** [comment]
The issue arises when you use `&Foo` where `Foo` is a constant, such as an enum variant with no arguments. `a === b` desugars to `snapshot_equality(&a, &b)`, hence the error here.

**Comment by jscissr** [comment]
There is a workaround for this problem: You can write a pure function which returns the constant. This only works if the type is `Copy`.

```rust
#[pure]
// Work around Prusti limitation. ("unsupported constant type")
fn none<T: Copy>() -> Option<T> {
  None
}

#[requires(x === none())]
fn demo(x: Option<bool>) {}
```
