### ISSUE TITLE
Parsing the third postcondition fails.

### ISSUE THREAD

**Issue by frececroka** [viperproject/prusti-dev#127]
This is interesting.

### Example 1

Input:
```
#![feature(register_tool)]
#![register_tool(prusti)]

use prusti_contracts::*;

#[ensures(true ==> true)]
fn main() {}
```

Output:
```
Verification of 1 items...
Successful verification of 1 items
```

### Example 2

Input:
```
#![feature(register_tool)]
#![register_tool(prusti)]

use prusti_contracts::*;

#[ensures(true)]
#[ensures(true)]
#[ensures(true ==> true)]
fn main() {}
```

Output:
```
error: expected expression
error: aborting due to previous error
```

### What is going on?

The only difference is that the latter input has two additional `#[ensures(true)]` annotations.

In the first example, the `true ==> true` is turned into the following token tree: `["true", "(=, Joint)", "(=, Joint)", "(>, Alone)", "true"]`.

In the second example, the `true ==> true` is turned into the following token tree: `["true", "(=, Joint)", "(=, Alone)", "(>, Alone)", "true"]`.

`(=, Joint)` represents a [`Punct`](https://docs.rs/proc-macro2/1.0.19/proc_macro2/struct.Punct.html) with `Joint` spacing, `(=, Alone)` represents a `Punct` with `Alone` spacing.

Because the second `=` has `Alone` spacing in the second example, the `==>` is not interpreted as the implication operator, but rather as two operators `==` and `>`.

**Comment by frececroka** [comment]
This could be a problem with the macro expansion of the compiler. I looked closer at the `prusti_specs::ensures` function (which implements the `#[ensures(...)]` proc-macro) and displayed, on every invocation, the attribute token stream, the item token stream, as well as the resulting token stream returned by the function. This is the output for the first invocation:
```
true
```
```
(#, Alone) [ ensures ( true ) ] 
(#, Alone) [ ensures ( true (=, Joint) (=, Joint) (>, Alone) true ) ] 
fn main (  ) {  }
```
```
(#, Alone) [ prusti (:, Joint) (:, Alone) spec_only ] 
(#, Alone) [ prusti (:, Joint) (:, Alone) spec_id (=, Alone) "8d21d99da9b54e19aa531d9f0429824f" ] 
(#, Alone) [ prusti (:, Joint) (:, Alone) assertion (=, Alone) "{\"kind\":{\"Expr\":{\"spec_id\":\"8d21d99d-a9b5-4e19-aa53-1d9f0429824f\",\"expr_id\":101}}}" ] 
fn prusti_post_item_main_8d21d99da9b54e19aa531d9f0429824f ( result (:, Alone) (  ) ) { (#, Alone) [ prusti (:, Joint) (:, Alone) spec_only ] (#, Alone) [ prusti (:, Joint) (:, Alone) expr_id (=, Alone) "8d21d99da9b54e19aa531d9f0429824f_101" ] (|, Alone) (|, Alone) (-, Joint) (>, Alone) bool { true } (;, Alone) } 
(#, Alone) [ prusti (:, Joint) (:, Alone) post_spec_id_ref (=, Alone) "8d21d99da9b54e19aa531d9f0429824f" ] (#, Alone) [ ensures ( true ) ] 
(#, Alone) [ ensures ( true (=, Joint) (=, Joint) (>, Alone) true ) ] 
fn main (  ) {  }
```

On the first invocation, the token stream for the item has the correct jointness, i.e., `(=, Joint) (=, Joint) (>, Alone)`. Also, the output of the first invocation preserves this correct jointness.

This is the output for the second invocation:
```
true
```
```
(#, Alone) [ ensures ( true (=, Joint) (=, Alone) (>, Alone) true ) ] 
(#, Alone) [ prusti (:, Joint) (:, Alone) post_spec_id_ref (=, Alone) "8d21d99da9b54e19aa531d9f0429824f" ] 
fn main (  ) {  }
```
```
(#, Alone) [ prusti (:, Joint) (:, Alone) spec_only ] 
(#, Alone) [ prusti (:, Joint) (:, Alone) spec_id (=, Alone) "199785eba9f34518a61305d58d4cf459" ] 
(#, Alone) [ prusti (:, Joint) (:, Alone) assertion (=, Alone) "{\"kind\":{\"Expr\":{\"spec_id\":\"199785eb-a9f3-4518-a613-05d58d4cf459\",\"expr_id\":101}}}" ] 
fn prusti_post_item_main_199785eba9f34518a61305d58d4cf459 ( result (:, Alone) (  ) ) { (#, Alone) [ prusti (:, Joint) (:, Alone) spec_only ] (#, Alone) [ prusti (:, Joint) (:, Alone) expr_id (=, Alone) "199785eba9f34518a61305d58d4cf459_101" ] (|, Alone) (|, Alone) (-, Joint) (>, Alone) bool { true } (;, Alone) } 
(#, Alone) [ prusti (:, Joint) (:, Alone) post_spec_id_ref (=, Alone) "199785eba9f34518a61305d58d4cf459" ] 
(#, Alone) [ ensures ( true (=, Joint) (=, Alone) (>, Alone) true ) ] (#, Alone) [ prusti (:, Joint) (:, Alone) post_spec_id_ref (=, Alone) "8d21d99da9b54e19aa531d9f0429824f" ] 
fn main (  ) {  }
```

Now on the second invocation, the token stream for the item has the wrong jointness, i.e., `(=, Joint) (=, Alone) (>, Alone)`.

It seems that at some point between us returning the new token stream from the first `prusti_specs::ensures` call and the compiler invoking the `prusti_specs::ensures` function for the second `#[ensures(true)]` annotation, the jointness is mixed up.

**Comment by frececroka** [comment]
I can reproduce this independently of Prusti, so this seems to be an issue with the Rust compiler.

**Comment by vakaras** [comment]
@karlosss You already fixed this one, right?

**Comment by karlosss** [comment]
Yup, this one is hopefully fixed. I will prepare a PR once I come home.

**Comment by frececroka** [comment]
Did you fix the Rust compiler or implement a workaround in Prusti?

**Comment by karlosss** [comment]
With @vakaras we decided to accept `== >` as the implies operator as well.

**Comment by frececroka** [comment]
I couldn't help myself and looked into the Rust compiler to see what the root cause is ;)

During the macro expansion, token streams are pretty-printed and the resulting string is parsed again. The pretty-printing is (wrongly) inserting a space between `==` and `>`, even though the token stream is stating that these two tokens are joined.

I fixed it in https://github.com/frececroka/rust/commit/ff9bfd0e7eb2341ec5713a001e4ab8b33e39e5ff and will probably open a PR for the Rust compiler soon. Let's see if this gets accepted.

**Comment by karlosss** [comment]
@frececroka thanks a lot for your activity there! If it gets accepted, I can just revert that not-very-nice solution we have now.

**Comment by Aurel300** [comment]
@frececroka Did you also figure out why it only pretty-prints wrong when it's the third attribute?

**Comment by frececroka** [comment]
I'm not exactly sure why it only fails on the third attribute. I'd expect it to fail on the second attribute already, but this is not the case.

Anyways, the pretty-printing seems to rely on special handling of some special cases, and the fix from https://github.com/frececroka/rust/commit/ff9bfd0e7eb2341ec5713a001e4ab8b33e39e5ff is interfering with these special cases and causes some tests to fail (because they expect more spaces in the pretty-printed output). I am not sure what the correct way to fix it is. Just testing for our exact combination of `==` and `>` is most likely not it.

**Comment by vakaras** [comment]
I have merged the workaround into master.

**Comment by frececroka** [comment]
I will close this for now and let you know when/if I get around to making a PR to rustc. If someone else wants to pick it up in the meantime feel free.
