### ISSUE TITLE
Cargo ignores flags from command-line

### ISSUE THREAD

**Issue by cedihegi** [viperproject/prusti-dev#1272]
When running the command: 
```
../../prusti-main/target/debug/cargo-prusti -- -Pcheck_overflows=false
```

the output still contains the following:

```
error: [Prusti: verification error] assertion might fail with "attempt to add with overflow"
  --> src/main.rs:12:5
   |
12 |     x + y
   |     ^^^^^
```

Either this is a bug or a problem in the dev-guide, since that's the instruction in there on how to use these flags. I have noticed the same problem for various other flags, so I'd assume it happens for all of them.
In case I am just not using them correctly I would be very thankful for a correction (and maybe an update in the dev-guide in the chapter on flags).

**Comment by JonasAlaif** [comment]
Please read [here](https://viperproject.github.io/prusti-dev/dev-guide/config/providing.html#commandline-arguments).
