### ISSUE TITLE
Cannot detect if code is getting verified by Prusti or compiled normally

### ISSUE THREAD

**Issue by Patrick-6** [viperproject/prusti-dev#1295]
The following code works when verified with Prusti, but fails in normal Cargo, since the predicate is not present when not compiled with Prusti. There does not seem to be a way to detect that Prusti is running and to add the `use` statement conditionally:
```rust
use prusti_contracts::*;

// #[cfg(feature = "prusti")] // Doesn't work
use other::pred;

#[requires(pred())]
fn test() {}

mod other {
    use prusti_contracts::*;

    predicate! {
        pub fn pred() -> bool {
            true
        }
    }
}
```
Cargo check gives this error on `use other::pred;`:
```
unresolved import `other::pred`
no `pred` in `import_prusti_predicate::other`
```

**Comment by Aurel300** [comment]
An alternative solution I suppose is to make sure `predicate!` still creates an item, but maybe it could be a ZST `const`, e.g. `const pred: () = ();`
