### ISSUE TITLE
Broken Links in README.md

### ISSUE THREAD

**Issue by indo-dev-0** [viperproject/prusti-dev#133]
The following links to examples annotated code are broken:
* `https://github.com/viperproject/prusti-dev/blob/master/prusti/tests/verify/pass-overflow/rosetta`
* `https://github.com/viperproject/prusti-dev/blob/master/prusti/tests/verify/pass/rosetta`

**Comment by vakaras** [comment]
We are currently upgrading Prusti to work with the newest version of the Rust compiler. As a result, almost all documentation is outdated. We are planning to fix it as soon as the upgrade is done.
