### ISSUE TITLE
Getting the external crates

### ISSUE THREAD

**Issue by trj2059** [viperproject/prusti-dev#140]
The verifier works fine when installing from the VSCode, however I can't seem to find instructions on getting the external crates so you can compile with the annotations.   Are there instructions somewhere in the codebase?

**Comment by vakaras** [comment]
This is not supported yet. @karenhong maybe could tell more about the status of this feature.

**Comment by fpoli** [comment]
Related: #2

**Comment by fpoli** [comment]
> getting the external crates

Do you mean the `prusti_contracts` external crate or crates with annotations published on crates.io? The former should work even outside VSCode, while the latter case is what is not yet supported.

**Comment by fpoli** [comment]
Closing as duplicate of #2
