### ISSUE TITLE
Support for Assume(False) in the VIR

### ISSUE THREAD

**Issue by eqfy** [viperproject/prusti-dev#142]
It would be really nice if someone can quickly implement support for Assume statements in the VIR. Alternatively, a specialized AssumeFalse statement is also sufficient. 

The reason behind this is because I use an assume false statement when encoding threads. Please let me know if you have any questions. Thanks!

**Comment by cmatheja** [comment]
Can't you use an `inhale` statement instead? 

The corresponding section in the [Viper tutorial](http://viper.ethz.ch/tutorial/?page=1&section=#assertion-checking) states that
```assume E is equivalent to inhale E; note that it takes an expression rather than an assertion, which must not contain resource assertions such as accessibility predicates```.

**Comment by eqfy** [comment]
Sorry for not realizing that, I somehow thought that since inhales and assumes do slightly different things, I wasn't able to replace assumes with inhales.
Thank you for clarifying!

**Comment by vakaras** [comment]
@eqfy It is probably worth mentioning that assume statements in Viper are “just syntactic sugar” and do not exist in the AST. That is also the reason why there is no `Assume` statement in VIR.
