### ISSUE TITLE
External specification for std::cmp::Ord crashing Prusti 

### ISSUE THREAD

**Issue by nokunish** [viperproject/prusti-dev#1425]
Hi! I just noticed that providing 
```
#[extern_spec]
impl std::cmp::Ord for i32 {
    
    fn max(self, other: i32) -> i32;
    fn min(self, other: i32) -> i32;
} 
```
crashes Prusti, and the only function for the `std::cmp::Ord` that does not crash is `cmp(..)`.

**Comment by Aurel300** [comment]
The reason for this is the same as discussed in #1436. Both `max` and `min` are methods provided by the `Ord` trait by default: there is no implementation of these methods by `i32`, so the extern spec is not "well-formed".
