### ISSUE TITLE
Details: Location bb15[12] has not yet been encoded

### ISSUE THREAD

**Issue by smokytheangel0** [viperproject/prusti-dev#1462]
Not entirely sure what this means in relation to what I am doing. I'm not even sure I know what I'm doing right now.
![Screen Shot 2023-10-16 at 14 11 40](https://github.com/viperproject/prusti-dev/assets/34082081/58b0d013-525b-4fd6-aaec-4f41ea8baa46)

**Comment by smokytheangel0** [comment]
I think it has to do with referenced typed fields?

**Comment by fpoli** [comment]
Thank you for the report. "Internal errors" are in 99% of the cases a bug in the implementation of our tool, as the error message suggests. Could you provide a minimal example to reproduce the bug? Without that, we cannot debug this.

**Comment by fpoli** [comment]
Feel free to reopen if you have a minimal example.
