### ISSUE TITLE
rustc removed plugins

### ISSUE THREAD

**Issue by safinaskar** [viperproject/prusti-dev#1473]
rustc just removed plugins ( https://github.com/rust-lang/rust/pull/116412 ). It is possible you are affected

**Comment by bjorn3** [comment]
Prusti uses the driver interface which isn't removed. Only `#![plugin(foo)]` is.

**Comment by fpoli** [comment]
Thank you for the heads up! We briefly experimented using the plugins interface years ago, but we no longer use it.
