### ISSUE TITLE
Prusti encounters unexpected internal error 

### ISSUE THREAD

**Issue by lpnaunau** [viperproject/prusti-dev#1523]
Hi, 

I'm quite new to Rust/Prusti, so it's probably an issue on my side but the following code generates an unexpected error. 
I attached the file as requested:
[rustc-ice.txt](https://github.com/user-attachments/files/16323744/rustc-ice.txt)

```
extern crate prusti_contracts;
use prusti_contracts::*;

#[pure]
fn sqr(x: i32) -> i32 {
    x * x
}

#[pure]
fn is_square(y: i32) -> bool {
    exists(|z: i32| y == sqr(z), y)
}

#[pure]
#[ensures(if x <= 0 { result == 0 } else { result == sum_of_odd(x - 1) + 2 * x - 1 })]
fn sum_of_odd(x: i32) -> i32 {
    if x <= 0 {
        0
    } else {
        sum_of_odd(x - 1) + 2 * x - 1
    }
}

#[pure]
#[requires(x >= 0)]
#[ensures(sum_of_odd(x) == sqr(x))]
fn sum_of_odd_is_sqr(x: i32) {
    if x > 0 {
        sum_of_odd_is_sqr(x - 1);
    }
}

#[requires(x < 0x10000)]
#[ensures(result == sum_of_odd(x as i32) as u32)]
fn compute_sum_of_odd(x: u32) -> u32 {
    let mut s: u32 = 0;
    let mut i: u32 = 0;
    while i < x {
        body_invariant!(s == sum_of_odd(i as i32) as u32);
        sum_of_odd_is_sqr(i as i32);
        s += 2 * i + 1;
        i += 1;
    }
    s
}

#[requires(x < 0x10000)]
pub fn test(x: u32) {
    let y = compute_sum_of_odd(x);
    sum_of_odd_is_sqr(x as i32);
    assert!(is_square(y as i32));
}
```

Thanks for your support.

**Comment by vakaras** [comment]
Based on the stack trace, the crash happens during the encoding of specifications or pure functions. It is illegal to use quantifiers inside pure functions, so I suspect that the crash is caused by `is_square`: 

```rust
#[pure]
fn is_square(y: i32) -> bool {
    exists(|z: i32| y == sqr(z), y) // Illegal syntax.
}
```

By the way:

1. Existentials are typically hard for SMT solvers. Therefore, it is recommended to use a concrete witness instead.
2. `x * x` is an example of non-linear integer arithmetic, which is undecidable.

**Comment by Aurel300** [comment]
In addition to @vakaras comment, if you *do* want to wrap specification-only code into a "function", you can do so with a [predicate](https://viperproject.github.io/prusti-dev/user-guide/verify/predicate.html). Predicates can only be called from specifications, such as pre- and postconditions, so your `assert!` would also have to be changed to a `prusti_assert!`.

**Comment by lpnaunau** [comment]
Thank you for your help, I'll have a look! Thx !
