### ISSUE TITLE
Loop invariants don't work

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#162]
A regression of the compiler upgrade is that loop invariants are ignored. For example, the following verifies, but it should generate a verification error.

```rust
use prusti_contracts::*;

pub fn simple_loop() {
    let mut x = 0;
    while x < 100 {
        body_invariant!(false); // Should fail
        x += 1;
    }
}

fn main() {}
```

**Comment by Aurel300** [comment]
I'll try to investigate this. So far it seems that `ProcedureEncoder::get_loop_spec_blocks` returns an empty vector even if the desugared Rust shows the invariant generated.

**Comment by Aurel300** [comment]
https://github.com/viperproject/prusti-dev/commit/813c127ae3da75a1c8ef0fb087367da48cb9931a#diff-1fb946419baeafc95d895e440b15e66eR280 might be the problem.

**Comment by vakaras** [comment]
The problem is in [the visitor](https://github.com/viperproject/prusti-dev/blob/58c11b21d29aa9433a118008f768d4bc4b0bd2a9/prusti-interface/src/specs/mod.rs#L36) that collects specifications. That visitor currently collects specs only for items.

**Comment by fpoli** [comment]
After PR #176 Prusti crashes instead of ignoring the invariants.
