### ISSUE TITLE
Incorrect span of failing pure function postcondition

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#167]
The following program has a verification error that is reported in the wrong place.

```rust
use prusti_contracts::*;

#[pure]
#[requires(n > 0)]
#[ensures(result == 5)] // <-- The error should be reported here
fn magic(n: i32) -> i32 {
    n
}

fn main() {}
```

Output:
```
error: [Prusti: verification error] postcondition of pure function definition might not hold
 --> prusti-tests/tests_old/verify/fail/issues/issue-81.rs:1:1
  |
1 | / use prusti_contracts::*;
2 | |
3 | | #[pure]
4 | | #[requires(n > 0)]
  | |__________________^
  |
note: the error originates here
 --> prusti-tests/tests_old/verify/fail/issues/issue-81.rs:1:1
  |
1 | / use prusti_contracts::*;
2 | |
3 | | #[pure]
4 | | #[requires(n > 0)]
  | |__________________^
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Aurel300** [comment]
This is the same kind of problem I found in the external specs PR: https://github.com/viperproject/prusti-dev/pull/145#issuecomment-693449852

**Comment by fpoli** [comment]
This is caused by https://github.com/rust-lang/rust/issues/43081

**Comment by fpoli** [comment]
The problem is caused by the recursive application of procedural macros. Considering the initial program, the `pure` macro is applied first, then the  `requires` macro is applied on the result of the first, then the `ensures` macro is applied on the result of the second. In this process, the compiler loses some information on the spans.

The fix is to do all the rewriting in the first macro. Considering the initial program, the `pure` macro should detect the `requires` and `ensures` attributes, should perform all the rewriting required by the three macros, and should then disable the remaining macros to avoid them from being applied next.

The relevant file in which to start implementing this is `prusti-specs/src/lib.rs`.

**Comment by fpoli** [comment]
Closed by mistake
