### ISSUE TITLE
Atom plugin?

### ISSUE THREAD

**Issue by jon-chuang** [viperproject/prusti-dev#18]
Since some integration with VSCode was done, I wonder if the same can be done for Atom, and what modules would need to be integrated.

**Comment by fpoli** [comment]
We don't plan to provide a plugin for Atom, but my guess is that it shouldn't be too difficult. Prusti outputs verification errors using rustc's error reporting infrastructure. So, any Atom plugin that parses the output of cargo or rustc to report errors on the source code should automatically handle as well the verification errors that Prusti generates. In the simplest case it's enough to replace `cargo build` with `cargo prusti` in the source code of the plugin.
