### ISSUE TITLE
Prusti for crypto?

### ISSUE THREAD

**Issue by jon-chuang** [viperproject/prusti-dev#19]
In https://github.com/project-everest/hacl-star/issues/277 I describe the seed of a proposal to apply verification in Rust to verified crypto. 

Project everest is a verified cryptographic library and associated tooling in F* that embeds a restricted set of C (Low*) and x64 assembly (Vale),  reasons about registers and memory model, alongside symbolic execution and tries to ensure that a highly optimised and often opaque cryptographic implementation conforms to a spec, which can be written in a more transparent form.

Here is the state of crypto in Rust:

> Rust is used extensively in the blockchain community for cryptographic implementation due to it's type safety and competitive performance with C++/C. A lot of new crypto (MPC, pairings, aggregated signatures, VDFs) is being implemented by this community. Just like with candidate post-quantum crypto, this presents an opportunity to test how verification applies to a wider subset of crypto.

I am wondering what the state of Prusti is, and what limitations might exist in pursuing such a project.

**Comment by fpoli** [comment]
Verifying low-level and other common Rust features is still on our roadmap, so Prusti will become in the future a reasonable option for such a project. However, it also heavily depends on what kind of properties you need to prove. Crypto code typically requires non-trivial proofs, which may not be within the reach of the underlying SMT solver, Z3, which we use.

**Comment by fpoli** [comment]
Let us know if you have any additional questions
