### ISSUE TITLE
[Documentation] dead links in the book

### ISSUE THREAD

**Issue by giltho** [viperproject/prusti-dev#23]
Hi ! I was interested in understanding how Prusti works. In particular, how you link the the rust compiler and MIR.

I built the book in `design`, but [the link given for the documentation of the patched Rust compiler](https://github.com/viperproject/prusti-dev/blob/master/design/src/01_introduction.md#L4) is dead.
I realise it was written two years ago, but is there any chance you still have that documentation somewhere ? Even in raw format :)

Thank you !

**Comment by vakaras** [comment]
Hello! We are currently upgrading Prusti to work with the latest version of the compiler. The planed way of integrating Prusti with Rustc is to use the same approach as MIRAI, MIRI, and Clippy uses.

By the way, in the last two years, the compiler team made significant progress of describing the compiler internals: https://forge.rust-lang.org/compiler/index.html

**Comment by giltho** [comment]
Thank you so much for your answer !
That's great, I think you gave me enough pointer to find the rest on my own :)

Closing the issue :)
