### ISSUE TITLE
Proper shutdown of prusti-server

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#249]
Sending a SIGINT to `prusti-server` should ensure that all its (transitive) children are killed.

**Comment by vakaras** [comment]
I think that `prusti-server` should ensure that **all** its (transitive) children are killed.

**Comment by fpoli** [comment]
> I think that `prusti-server` should ensure that **all** its (transitive) children are killed.

Yes. Making this cross-platform might be tricky.

**Comment by fpoli** [comment]
This is another good first issue for new contributors!

Please ask for more information in case you are interested.

**Comment by gavinleroy** [comment]
Hi, I would be interested in working on this issue. 

Is there further information on the issue or a way to reproduce the bug?

**Comment by fpoli** [comment]
On Ubuntu, here is how I can reproduce it:

1. Start the server in one terminal: `./target/debug/prusti-server --port 1234`
2. In another terminal, run `ps a | grep prusti | grep -v grep`. You should see a `prusti-server` process and its child `prusti-server-driver`. For example:
    ```
    18163 pts/19   S+     0:00 ./target/debug/prusti-server --port 1234
    18164 pts/19   Sl+    0:00 /home/fpoli/src/prusti/prusti-dev/target/debug/prusti-server-driver --port 1234
    ```
3. Send a `SIGINT` to the parent process with e.g. `kill -s SIGINT 18163`.
4. Rerun `ps a | grep prusti | grep -v grep`. You should see that `prusti-server-driver` is still alive.

Note that if instead of `kill -s SIGINT ...` you kill the server with `Ctrl-C` in the first terminal then all the processes die and you don't see the issue, because [`Ctrl-C` sends a `SIGINT` to all the processes in the foreground process group](https://stackoverflow.com/a/8406413/2491528).

**Comment by fpoli** [comment]
When you verify a program while the server is running, `prusti-server-driver` runs Viper in a JVM thread, which in turn spawns additional `z3` or `boogie` processes. As far as I know, Viper doesn't guarantee to stop all those processes when the JVM gets stopped. So, both the Prusti and Viper IDE extensions use [tree-kill](https://github.com/pkrumins/node-tree-kill), whose implementation first obtains the tree of processes and then sends a signal to each of them. The ideal solution to this issue is to move that logic inside `prusti-server`, such that a `SIGINT` to the server guarantees to stop all subprocesses.

If you ever need it, a command to launch a long-running verification is the following
```
PRUSTI_SERVER_ADDRESS="localhost:1234" ./target/debug/prusti-rustc --edition=2018 -Awarnings ./prusti-tests/tests/verify/pass/rosetta/Knights_tour.rs
```
After the server shows "Starting: verification" you should see a bunch of `z3` processes. However, on my Ubuntu I didn't manage to kill the server in a way that keeps the `z3` processes running. Probably on MacOS or Windows the behavior is different.

(@ArquintL do you happen to know cases in which stopping Viper leaves some `z3` instances alive?)
