### ISSUE TITLE
Support type casting for numeric values

### ISSUE THREAD

**Issue by kammola** [viperproject/prusti-dev#252]
Applying arithmetic operations and comparison between different numeric types should be allowed, e.g. ("#[ensures (result > 100 * i)]" if result is i32 and I is i32).

**Comment by kammola** [comment]
@vakaras

**Comment by fpoli** [comment]
Lossless integer casts (e.g. `i32` -> `u128` etc) should already be supported.

**Comment by kammola** [comment]
> Lossless integer casts (e.g. `i32` -> `u128` etc) should already be supported.

what about usize -> i32, that should be possible if we can ensure an upper bound on the value.

**Comment by fpoli** [comment]
> what about usize -> i32, that should be possible if we can ensure an upper bound on the value.

That's not supported, but it should be easy to encode the cast as a pure Viper `Int -> Int` function call, with a precondition that checks that the input value is in the range of the output type.

**Comment by fpoli** [comment]
It's also easy to support numeric casts when overflow checks are disabled. It's matter of adding one branch to the `encode_cast_expr` in `mir_encoder.rs`.
