### ISSUE TITLE
ICE unexpected panic called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by tillarnold** [viperproject/prusti-dev#265]
@vakaras @cmatheja: Verifying the following program fails with `thread 'rustc' panicked at  'called Option::unwrap() on a None value', prusti-viper/src/encoder/procedure_encoder.rs:2225:36`

To reproduce set  `PRUSTI_LOG="debug"` to ensure the `debug!` statement that causes the panic is executed.

```rust
use prusti_contracts::*;

#[derive(PartialEq, Eq)]
struct List {
    next: Option<Box<List>>,
}

impl List {
    #[pure]
    fn len(&self) -> usize {
        match &self.next {
            Some(n) => 1 + n.len(),
            None => 1,
        }
    }
}

fn main() {}
```

**Comment by cmatheja** [comment]
The panic certainly should not happen; I'll need to investigate.

**Comment by fpoli** [comment]
@cmatheja I think it's just the argument of `debug!(..)` that is wrong.

**Comment by cmatheja** [comment]
> @cmatheja I think it's just the argument of `debug!(..)` that is wrong.

Ah okay. I thought there might be another cause related to the fact that snapshots of Options/enums (which are not really needed in this example) are not supported in master yet. I'll still take this issue as a reason to rectify this.

**Comment by vakaras** [comment]
> which are not really needed in this example

They are kind of needed. Just it would not be the **minimal** crashing example ☺.

If I understand correctly, adding the following function should cause the snapshots to be generated:

```rust
fn check(x: List, y: List) {
    assert!(x == y);
}
```

Am I right?

**Comment by cmatheja** [comment]
> Am I right?

Prusti would detect that not every field of List is supported and generate a stub for the equality instead of using snapshots. So this should not crash - it's just very very incomplete :-) Anyway, I agree that this should be addressed soonish.

**Comment by Aurel300** [comment]
Does not crash anymore, with or without a (pure or impure) `check` method. [`verify/pass/pure-fn/len-lookup.rs`](https://github.com/viperproject/prusti-dev/blob/b152e5a8786fce65dc34990ee50a9050b365f7f9/prusti-tests/tests/verify/pass/pure-fn/len-lookup.rs)
