### ISSUE TITLE
Procedure IDs not found when encoding stubs

### ISSUE THREAD

**Issue by cmatheja** [viperproject/prusti-dev#286]
Encoding stubs of non-local functions crashes Prusti because their def_id cannot be resolved. We fixed this issue some time ago (see #188) by using `optimized_mir` instead of `mir_promoted`. However, this change seems to have been [reverted](https://github.com/viperproject/prusti-dev/commit/67ba49af1a83cb0c5950e4da5ac836e5d4c4f866#diff-72b8cdf78b692df9a1bc2b00f69ae756d76705fb45acd097675960580392af66L1375-R1400). 

Now, the following program crashes Prusti again:

```rust
use prusti_contracts::*;

// should create stub for cmp::PartialOrd::lt 
#[derive(PartialEq,PartialOrd)]
struct A {
    i: i32,
}

#[requires(_x < _y)]
fn test(_x: A, _y: A) {
}

fn main() {
}

```

Interestingly, switching back from `self.env.mir(proc_def_id.expect_local())` to `self.env.tcx().optimized_mir(proc_def_id)` does *not* resolve the issue; the above example still crashes with the following error:

```
get_optimized_mir: missing MIR for `DefId(2:1772 ~ core[5bc6]::cmp::PartialOrd::lt)` 
```

Is this caused by a recent change in the compiler?

**Comment by vakaras** [comment]
> However, this change seems to have been reverted.

I suspect that this happened by accident when upgrading something.

> the above example still crashes with the following error:
> ```
> get_optimized_mir: missing MIR for `DefId(2:1772 ~ core[5bc6]::cmp::PartialOrd::lt)` 
> ```
> Is this caused by a recent change in the compiler?

I am confused. Why `core[5bc6]::cmp::PartialOrd::lt` should have MIR? Isn't it an abstract trait method that does not have body and hence MIR?

**Comment by cmatheja** [comment]
> I am confused. Why `core[5bc6]::cmp::PartialOrd::lt` should have MIR? Isn't it an abstract trait method that does not have body and hence MIR?

I guess previously we just got an empty body. That was fine because `StubFunctionEncoder` uses MIR only to get the types of the arguments and whatever is returned. Now, however, we get the above error instead.

**Comment by Aurel300** [comment]
If `StubFunctionEncoder` only uses this for the argument types, would the types from the `Call` terminator not be sufficient? We have this information in the `PartialEq` calls, for example.

https://github.com/viperproject/prusti-dev/blob/4432b723abd01cf57ecf8760e16766a04c646386/prusti-viper/src/encoder/pure_function_encoder.rs#L714-L726

**Comment by fpoli** [comment]
> However, this change seems to have been reverted.

If it's not tested it will break :stuck_out_tongue_winking_eye: 

Do you remember it working before the compiler upgrade or also after it?

**Comment by fpoli** [comment]
Ah, now I get why it's a regression. Christoph pointed me to [this line](https://github.com/viperproject/prusti-dev/commit/67ba49af1a83cb0c5950e4da5ac836e5d4c4f866#diff-72b8cdf78b692df9a1bc2b00f69ae756d76705fb45acd097675960580392af66L1377-R1399). I didn't mean to replace optimized with promoted MIR.

**Comment by Aurel300** [comment]
I don't know if we even need the stub function encoder anymore (it is used in one place only, when the encoding of a pure function definition fails). The code from the issue now correctly reports that `<` (`PartialCmp::lt`) is not pure and this is solved with an `extern_spec`.
