### ISSUE TITLE
Deploy fails due to rustup

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#304]
The deploy script is currently failing due to an error of `rustup self update` on `macos-latest`. This issue didn't show up until I fixed the name conflict in the boogie package.

**Comment by Aurel300** [comment]
I guess we shouldn't even need to run self-update on CI, since we get a fresh `rustup` installation anyway?

**Comment by fpoli** [comment]
Unfortunately the new `rust-toolchain` format requires `rustup v1.23.0`, while the `rustup` provided in the `macos-latest` runner is a bit older. One option, of course, is to revert to the old `rust-toolchain` format, but I was hoping for another solution.

**Comment by fpoli** [comment]
It seems that Github updated the `rustup` version in `macos-latest`.
