### ISSUE TITLE
Trait refinement verifies contracts are legal but then doesn't use them

### ISSUE THREAD

**Issue by f4z3r** [viperproject/prusti-dev#34]
According to the source code, contract refinement on trait methods [should be supported][1] with pre-condition weakening and post-condition strengthening. This is enforced in the sense that it is checked that the pre-/post-condition on the implementation is weaker/stronger respectively, but the verification does not take these contracts into account:

[1]: https://github.com/mario-bucev/prusti-dev/blob/3f702b4679b7c2a471a5890b8e0b68f334fcd07b/prusti-viper/src/encoder/error_manager/mod.rs#L457

```rust
extern crate prusti_contracts;

trait Answer {
    #[requires="_arg == 1"]
    #[ensures="result >= - 100 && result <= 100"]
    fn produce_answer(&self, _arg: i32) -> i32;
}

struct DeepThought {}

impl Answer for DeepThought {
    #[requires="true"]
    #[ensures="result == 42"]
    fn produce_answer(&self, _arg: i32) -> i32 { 42 }
}

fn test(dt: &DeepThought) {
    let answer = dt.produce_answer(40);

    assert!(answer == 42);
}

fn main() {
    let dt = DeepThought {};
    test(&dt);
}
```

The code above doesn't verify as it complains that the call to `produce_answer` doesn't have 1 as an argument. Even if this is changed, it doesn't verify with "the asserted expression might not hold", implying the post-condition is also not taken into account.

**Comment by Aurel300** [comment]
Works now. Probably as a result of #795.
