### ISSUE TITLE
Broken overflow checks?

### ISSUE THREAD

**Issue by mabbamOG** [viperproject/prusti-dev#340]
The following program compiles just fine with cargo-prust (and extra env variable: `PRUSTI_CHECK_BINARY_OPERATIONS=true`):

```Rust
use prusti_contracts::*;

#[pure]
#[ensures(result >= a && result >= b)]
#[ensures(result == a || result == b)]
fn max(a: i32, b: i32) -> i32 {
    if a < b {
        b
    } else {
        a
    }
}

#[pure]
#[ensures(result == a + b)]
fn add(a:u8, b:u8) -> u8 {
    a + b
}

pub fn main() {
    max(3,4);
    add(255, 255);
}
```

while its equivalent pure-Rust version panics at runtime execution.

**Comment by Aurel300** [comment]
Can you try with `PRUSTI_CHECK_OVERFLOWS`? We renamed this recently #260.

**Comment by fpoli** [comment]
Using `PRUSTI_CHECK_OVERFLOWS` Prusti reports a correct error message for the `a + b` in `add`:

```
[Prusti: verification error] assertion might fail with "attempt to add with overflow"
```
