### ISSUE TITLE
Test fails (on Windows?): NLL log directory not found

### ISSUE THREAD

**Issue by ELowis** [viperproject/prusti-dev#341]
The test for "pass\extern-spec\swap.rs" fails on my Windows computer, even when I am on the unmodified master at commit 95409028b9acbd77fa5ca516ad0d2e4f1d21b298 and have deleted the ``target`` and ``prusti-test\log`` directories and have rerun ``x.py build`` before running ``x.py test``. All other tests succeed (when I ignore this test case).

Here is the test output:
```
...
test [run-pass] pass\extern-spec\swap.rs ...
error: compilation failed!
status: exit code: 101
command: 
PATH=";~\Prusti\prusti-dev\target\debug\build\ring-82eb85b9280213f5\out;
~\Prusti\prusti-dev\target\debug\deps;
~\Prusti\prusti-dev\target\debug;
C:\Users\L\.rustup\toolchains\nightly-2021-01-01-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib;
C:\Users\L\.cargo\bin;
C:\Users\L\.rustup\toolchains\nightly-2021-01-01-x86_64-pc-windows-msvc\bin;
...
C:\Program Files\Common Files\Oracle\Java\javapath;
...
C:\Program Files\Java\jdk-15.0.1\bin\server" 

"..\\target\\debug\\prusti-rustc.exe" "tests\\verify\\pass\\extern-spec\\swap.rs" 
"-L" "C:\\Users\\L\\AppData\\Local\\Temp\\" 
"--target=x86_64-pc-windows-msvc" 
"--error-format" "json" 
"-C" "prefer-dynamic" 
"-o" "C:\\Users\\L\\AppData\\Local\\Temp\\extern-spec\\swap.stage-id.exe" 
"--color=never" 
"--edition=2018" 
"-A" "warnings" 
"-L" "C:\\Users\\L\\AppData\\Local\\Temp\\extern-spec\\swap.stage-id.aux"

stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: 
Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." }', compiler\rustc_mir\src\borrow_check\nll.rs:280:62
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose bac
ktrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-d
ev/issues/new
note: Prusti version: {commit 95409028 2021-01-04 11:13:17 UTC, built on 2021-01
-06 10:45:10 UTC}

query stack during panic:
#0 [mir_borrowck] borrow-checking `stde329e49ab9e74db2afab6632de1fd065::mem4c558
d9a571d46f287346563289352a8::prusti_post_item_swap_e330d52ac02349b39d251100a3b47
2e0::{closure#0}`
#1 [mir_borrowck] borrow-checking `stde329e49ab9e74db2afab6632de1fd065::mem4c558
d9a571d46f287346563289352a8::prusti_post_item_swap_e330d52ac02349b39d251100a3b47
2e0`
#2 [analysis] running analysis passes on this crate
end of query stack

------------------------------------------

FAILED

...
test failed, to rerun pass '-p prusti-tests --test compiletest'
```

This might also be a rustc bug. The panic occurs, because the operating/file system does not find the path to write the nll_facts to. As this only occurs for this one test case, it is probably not caused by the nll_facts_dir, but the translation of the def_path/def_id to a file name in ``def_path.to_filename_friendly_no_crate()`` at line 279 of compiler\rustc_mir\src\borrow_check\nll.rs. For swap I see a folder with contents in prusti-test\log\nll-facts, therefore, it might be another def_id/function inside that file.

**Comment by fpoli** [comment]
Could you check if you can manually crate the file `prusti-tests/log/nll-facts/std0ab0db53ecc54ce8a021ac18b47eef20-mem85349b076b4d40e9a887a9c8e85ff017-prusti_post_item_swap_efab9c14c6564aaf9d0dbdd23f0e37a0-{closure#0}/drop_of_var_derefs_origin.facts`? Maybe the folder name is too long.

**Comment by ELowis** [comment]
The folder name itself is not too long, but the whole path is too long due to the folder where I store prusti-dev. Thanks for providing the folder name! I can create the folder, but I can only name the file ``drop_of_var_dere`` and not any longer. That's due to the path length limit of 260 characters on NTFS/Windows: https://docs.microsoft.com/de-de/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
One can disable this limit in Windows 10, but the application needs to support it. I will just let the test runner ignore that test case for now.
The only other solution (except me enabling larger paths or moving the folder to another directory) would probably be that rustc reduces the length of the filenames for closures...
