### ISSUE TITLE
Bug: Dependencies seem to break Prusti: [E0432] unresolved import

### ISSUE THREAD

**Issue by Evrey** [viperproject/prusti-dev#360]
Full message for my use case:

> [E0432] unresolved import `uuid`.
>
> [Note] use of undeclared crate or module `uuid`

I toyed around, setting up Prusti for my project. It's a `workspace` project, and one of the workspace crates has `uuid` as its dependency. There's a `pub use uuid::Uuid;` somewhere in the `lib.rs`, which gets marked with this error.

To make things worse, it seems like Prusti doesn't do any verification, probably due to this very error. For example, i have this method here:
```Rust
	#[pure]
	#[requires(   self.game_id != Uuid::nil() )]
	#[requires(             id != Uuid::nil() )]
	#[ensures(  result.game_id != Uuid::nil() )]
	pub fn with_game_id(mut self, id: Uuid)
	-> Self {
		debug_assert!(!id.is_nil());

		self.game_id = id;

		self
	}
```
If i change `#[ensures(  result.game_id != Uuid::nil() )]` to a `==` comparison, it *should* fail any checks. But i still only get the `uuid` import error. However, if i change the `#[ensures()]` to contain invalid syntax, this syntax error will be reported normally, alongside the import error.

I have not yet made any external specs for `uuid`, given that the import allegedly fails.

The import error is not an error, however. Without Prusti, all the code compiles just fine and all unit tests succeed, etc. So it's a bug in Prusti.

I'm using the **VSCode Plugin** »Prusti Assistant« in **VSCodium**, build channel set to **LatestDev**. I'm always updating to the newest nightly before each session. Installed Java versions are OpenJDK 11 and 14, OS is Ubuntu.

**Comment by Evrey** [comment]
Oh, btw., forgot to mention… adding an extra `extern crate uuid;` for Prusti did not solve the problem. The error message is the same, but this time it points at the `extern crate uuid;`.

**Comment by vakaras** [comment]
Hello @Evrey, thank you for reporting this. Is your code public? (So that I can try it out on my machine?)

**Comment by Evrey** [comment]
@vakaras Hey there! Sadly not, I work closed-source. However, I made a super minimal sample project that mimics my set-up and has the very same error. https://github.com/Evrey/prusti_bug_min 

- Note that the `Cargo.toml` uses an unstable `cargo` feature. A bunch of Rust tools break trying to parse stable-only `Cargo.toml`s.
- Also note the `#![no_std]`.

These two are my personal best guesses at what may trigger the bug.

**Comment by vakaras** [comment]
Thank you for providing a minimal example! Your example seems to work from the command line:
```bash
git clone https://github.com/Evrey/prusti_bug_min.git
target/debug/cargo-prusti --manifest-path prusti_bug_min/Cargo.toml
```
gives
```plain
error: [Prusti: verification error] postcondition might not hold.
  --> hmm/src/lib.rs:9:11
   |
9  | #[ensures(result != 0)]
   |           ^^^^^^^^^^^
   |
note: the error originates here
  --> hmm/src/lib.rs:10:1
   |
10 | pub fn f() -> u32 { 0 }
   | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `hmm`

To learn more, run the command again with --verbose.
```
Therefore, it seems that the problem is in the IDE (I could reproduce the problem with my version of Prusti Assistant). @fpoli Do you have an idea what could be wrong here?

**Comment by fpoli** [comment]
Currently, the IDE can only verify programs that can be compiled with a simple `rustc <program.rs>` call. So, standalone files without Cargo dependencies. The code to support verification of crates from the IDE is almost ready.

**Comment by fpoli** [comment]
I move this issue to https://github.com/viperproject/prusti-assistant/issues/45
