### ISSUE TITLE
Error when using universal quantifies in pre/postcondition

### ISSUE THREAD

**Issue by Lee-Janggun** [viperproject/prusti-dev#363]
I have a function with postconditions as follows.

```rust
#[ensures(length(r) == old(length(r)))]
#[ensures(r.current.x == max(old(r.current.x), min_x))]
#[ensures(r.current.y == old(r.current.y))]
#[ensures(
    forall i: i32 :: (1 <= i && i < length(r))  ==> nth_x(r,i) == max(nth_x(r,i-1), old(nth_x(r,i))))
)]
fn force_inc(r: &mut Route, min_x: i32) { /*...*/ }
```
In the current state, Prusti gave an error `expecting (` after the `forall`. I changed the annotation into closure form as follows

```rust
#[ensures(
    forall(|i: i32| (1 <= i && i < length(r))  ==> nth_x(r,i) == max(nth_x(r,i-1), old(nth_x(r,i))))
)]
```
and Prusti verified just fine. I got the syntax for the first version from [here](https://viperproject.github.io/prusti-dev/user-guide/syntax.html#quantifiers). Is it possible that the guide is not updated?

**Comment by vakaras** [comment]
> Is it possible that the guide is not updated?

Yes, it seems that the guide has the wrong syntax. Thank you for reporting!
