### ISSUE TITLE
Overlapping shared references in pure functions are not supported

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#364]
Prusti generates incorrect encoding for the following program:

```rust
use prusti_contracts::*;

struct Child {}

struct Tree {
    child: Child,
}

#[pure]
fn use_both(_: &Tree, _: &Child) -> bool {true}

#[pure]
fn test(tree: &Tree) -> bool {
    use_both(tree, &tree.child)
}
```

The problem is that `test` is encoded as follows:
```javascript
function test(_1: Ref): Bool
  requires acc(Tree(_1), read$())
  requires true
  ensures true
{
  (unfolding acc(Tree(_1), read$()) in use_both(_1, _1.child))
}
```
which fails because we cannot have permissions to both `_1` and `_1.child` at the same time.

cc @tillarnold Purification should fix this bug.

**Comment by Aurel300** [comment]
Is there a way to make this work without purification?

**Comment by vakaras** [comment]
@Aurel300  In theory, we could use the wildcard permissions for this. However, Marco told me that they kill performance.

**Comment by fpoli** [comment]
@Aurel300 Should this be fixed by snapshots?

**Comment by Aurel300** [comment]
@fpoli Sure, there will be no permissions in the purified version of `test`, so passing the snapshot itself and separately using a field accessor on the snapshot and passing its result is fine.
