### ISSUE TITLE
Suggestion: update the docker image

### ISSUE THREAD

**Issue by rw** [viperproject/prusti-dev#393]
I see that the Makefile has a command for pushing docker images. I also see that the latest image on dockerhub is from two years ago (https://hub.docker.com/r/fpoli/prusti-base). Would it be possible to update these images? Thanks!

**Comment by rw** [comment]
One use case is running prusti in CI pipelines.

**Comment by fpoli** [comment]
The docker images are now available at https://hub.docker.com/r/viperproject/prusti and they are automatically updated. Could you confirm that they work for you?
