### ISSUE TITLE
Postcondition is unable to infer precondition from the same method

### ISSUE THREAD

**Issue by jmc-figueira** [viperproject/prusti-dev#483]
In this example:

```Rust
    #[trusted]
    #[pure]
    #[requires(index < self.len())]
    #[ensures(forall(|i: usize| (i < self.len()) ==> result == self.lookup(i)))]
    pub fn lookup(&self, index: usize) -> u64 {
        self.vec[index]
    }

    #[trusted]
    #[requires(index < self.len())]
    #[ensures(self.lookup(index) == new_value)]
    pub fn modify(&mut self, index: usize, new_value: u64) {
        self.vec[index] = new_value;
    }
```

The postcondition for `modify` is unable to use its own precondition to assert that the precondition for `lookup` is met, and produces the following error:

```Rust
error: [Prusti: verification error] precondition of pure function call might not hold.
  --> src/base/vec_wrapper.rs:50:15
   |
50 |     #[ensures(self.lookup(index) == new_value)]
   |               ^^^^^^^^^^^^^^^^^^
   |
note: the failing assertion is here
  --> src/base/vec_wrapper.rs:42:16
   |
42 |     #[requires(index < self.len())]
   |                ^^^^^^^^^^^^^^^^^^
```

This is not exactly an error with Prusti or the compilation process, but I thought I'd report it anyways since it might not be intended behavior.

**Comment by fpoli** [comment]
That's because the implementation of `modify` is in principle allowed to change the length, but the contract doesn't specify if the length actually changes or not. The error should go away if you add `index < self.len()` to the postcondition, before the `lookup` call.

**Comment by jmc-figueira** [comment]
Ah, I understand. Thanks for the clarification.
