### ISSUE TITLE
What is the advantage of prusti over unit testing?

### ISSUE THREAD

**Issue by dclong** [viperproject/prusti-dev#517]
It seems to me that some checks provided by prusti can also be done using unit testing. What is the main advantage of prusti over unit testing? 
(Please forgive my ignorance if the question is too stupid. I'm very new to Rust.)

**Comment by vakaras** [comment]
Testing allows checking whether a **single** execution does not violate an assertion. Prusti allows checking whether **all** executions do not violate the assertion.

**Comment by dclong** [comment]
Thanks a lot! That's interesting!
