### ISSUE TITLE
Set toolchain from cargo-prusti

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#52]
It would be nice to automatically set the `RUST_TOOLCHAIN` environment variable in the `cargo-prusti` binary.

**Comment by eqfy** [comment]
Hi, since we already have the rust-toolchain file which provides the RUSTUP_TOOLCHAIN value, I was wondering if this enhancement is to just set the environment variable based on this value?

**Comment by fpoli** [comment]
> Hi, since we already have the rust-toolchain file which provides the RUSTUP_TOOLCHAIN value, I was wondering if this enhancement is to just set the environment variable based on this value?

Yep. A correction: the environment variable should be set in the `cargo-prusti` binary, and the value should be read from `rust-toolchain` at compile time (not at run time) using something like [include_str](https://doc.rust-lang.org/std/macro.include_str.html).
