### ISSUE TITLE
Prusti does not preserve information about non-borrowed fields when mutably borrowing

### ISSUE THREAD

**Issue by dario23** [viperproject/prusti-dev#520]
sample code

```rust
use prusti_contracts::*;


fn main() {
    let mut x = Foo { x: 3, y: 42 };
    let xx = re_ref(&mut x);
    // xx expires

    // assert on the "leftover" of the magic wand, which by rust semantics can't have changed
    assert!(x.y == 42);
}

struct Foo {
    x: u32,
    y: u32,
}

fn re_ref(x: &mut Foo) -> &mut u32 {
    &mut x.x
}
```

prusti fails to verify this, because when calling `re_ref`, the full `write` permissions to `x` are `exhale`d (i.e. havocing all values for after the expiry of the reference), but the magic wand does not mention the non-borrowed fields, it's just `ref$u32(xx) --* Foo(x)` (modulo desugaring). mentioning the non-borrowed fields in the wand probably depends on more snapshot functionality, but could look somewhat like `ref$u32(xx) --* Foo(x) && snap(x.f$y) == old[before_borrow](snap(x.f$y))`

attaching [ref-mut.rs (source file)](https://github.com/viperproject/prusti-dev/files/6487600/ref-mut.rs.txt) and [ref-mut.rs.vpr (generated encoding)](https://github.com/viperproject/prusti-dev/files/6487603/ref-mut.rs.vpr.txt) for easier reproducing.

**Comment by fpoli** [comment]
I think that failing to verify the example is the correct behavior, because the *signature* of `re_ref` allows to modify `x.y` in it:

```rust
use prusti_contracts::*;

fn main() {
    let mut x = Foo { x: 3, y: 42 };
    let xx = re_ref(&mut x);
    // xx expires

    // assert on the "leftover" of the magic wand, which by rust semantics can't have changed
    assert!(x.y == 42);
}

struct Foo {
    x: u32,
    y: u32,
}

fn re_ref(x: &mut Foo) -> &mut u32 {
    x.y += 100;
    &mut x.x
}
```

So, if we don't attach a contract to `re_ref` specifying that `x.y` stays the same, then the only sound reasoning at the call site is to assume that the call might also modify `x.y`.

**Comment by Aurel300** [comment]
Yes, proving that assertion should not be possible with modular verification.

**Comment by dario23** [comment]
ah, makes sense.. sorry for the noise. :+1:
