### ISSUE TITLE
Regression: enum test fails with new viper-tools

### ISSUE THREAD

**Issue by dario23** [viperproject/prusti-dev#562]
this snippet from the quick tests enum.rs file seems to make prusti panic reproducibly, while verifying fine previously:
```
pub enum E3<T> {
    V1(T),
    V2(T),
}

pub fn test3<T>(e: &mut E3<T>) -> &mut T {
    match *e {
        E3::V1(ref mut b) => b,
        E3::V2(ref mut b) => b,
    }
}
```
`git bisect` seems to think it's related to the merge of #553, but that by itself got merged OK, and testing this locally using the exact viper tools version used in the PR verification build still fails, so i'm not sure what it actually is.

**Comment by vakaras** [comment]
The minimal Viper file causing the problem:
```
domain $T$_ {
  
  function f(self: $T$_): Int

}
```

Running Silicon by hand with `Z3_EXE=viper_tools/z3/bin/z3 java -cp viper_tools/server/viperserver.jar viper.silicon.SiliconRunner snap-debug.vpr` gives the following:

```
Silicon 1.1-SNAPSHOT (74cc106a)
Verification aborted exceptionally: java.util.concurrent.ExecutionException: viper.silicon.reporting.Z3InteractionFailed: Unexpected output of Z3. Expected 'success' but found: (error "line 107 column 65: unknown function/constant $SortWrappers.$T$__To$Snap")
  Cause: viper.silicon.reporting.Z3InteractionFailed: Unexpected output of Z3. Expected 'success' but found: (error "line 107 column 65: unknown function/constant $SortWrappers.$T$__To$Snap")
Silicon found 1 error in 2,80s:
  [0] Interaction with Z3 (instance 00) failed: Unexpected output of Z3. Expected 'success' but found: (error "line 107 column 65: unknown function/constant $SortWrappers.$T$__To$Snap")
```

cc @marcoeilers @mschwerhoff

**Comment by vakaras** [comment]
The strange thing is that the Viper toolchain is `v-2021-06-10-1132-nightly`, which is **before** Marco's change was merged. 

@fpoli @ArquintL Could it be that the versioning of the Viper toolchain is broken?

**Comment by vakaras** [comment]
The silicon commit that most likely introduced the error: https://github.com/viperproject/silicon/commit/aa3e7a563dd1504e89d4ab59f4e90ce96c57b45a. It seems that it is a really bad idea to use string manipulations in the frontend and backend at the same time…

**Comment by ArquintL** [comment]
@vakaras I've updated the artifacts for the [`v-2021-06-10-1132-nightly` release](https://github.com/viperproject/viper-ide/releases/tag/v-2021-06-10-1132-nightly) yesterday. As this still is a bootstrap release such that I can execute the test suite in the `viper-ide` repo I did only change the release's description and did not bother to update the tag and thus the tag is misleading. I'm sorry for that. https://github.com/viperproject/silicon/commit/74cc106af9e2ba038ca764b266b7e770b1140d65 has been used to create the release artifact

**Comment by vakaras** [comment]
> @vakaras I've updated the artifacts for the [`v-2021-06-10-1132-nightly` release](https://github.com/viperproject/viper-ide/releases/tag/v-2021-06-10-1132-nightly) yesterday. As this still is a bootstrap release such that I can execute the test suite in the `viper-ide` repo I did only change the release's description and did not bother to update the tag and thus the tag is misleading. I'm sorry for that. [viperproject/silicon@74cc106](https://github.com/viperproject/silicon/commit/74cc106af9e2ba038ca764b266b7e770b1140d65) has been used to create the release artifact

This solves one part of the mystery…

**Comment by vakaras** [comment]
I guess we can work around the problem on our side by adding `_` as a suffix to every generic parameter…

**Comment by ArquintL** [comment]
> This solves one part of the mystery…

@vakaras should I revert the release artifacts and create a proper new release (to which you currently do not update your toolchain)?

**Comment by vakaras** [comment]
> > This solves one part of the mystery…
> 
> @vakaras should I revert the release artifacts and create a proper new release (to which you currently do not update your toolchain)?

It seems that we found a workaround, so this should not be a problem anymore.
