### ISSUE TITLE
Add a test that checks that Prusti.toml is read by cargo prusti

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#571]
It seems that `Prusti.toml` is currently not read by `cargo prusti`. That should be fixed and we should have a test for this.

See [this Zulip topic](https://prusti.zulipchat.com/#narrow/stream/236614-general/topic/Some.20issues.20with.20forall) for details.

**Comment by fpoli** [comment]
For the test, we can add a folder to `prusti-tests/tests/cargo_verify` containing a crate with a `Prusti.toml`. Note that a corresponding function needs to be added at the end of [`cargotest.rs`](https://github.com/viperproject/prusti-dev/blob/fa410ea2ee85b4aeacbb7b79098fb9cfc86ee72c/prusti-tests/tests/cargotest.rs#L157-L162); there is no autodiscovery (yet).
