### ISSUE TITLE
Snapshot encoding ignores `old`

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#599]
For the following program:
```rust
use prusti_contracts::*;

#[derive(Clone,PartialEq,Eq)]
struct A {
    i: i32,
}

#[requires(_x == _y)]
#[ensures(old(_x) == old(_y))]
fn get_value(_x: A, _y: A) -> A {
    _x
}

fn main() {
}
```
Prusti generates the following VIR code for checking the postcondition:
```
// Assert functional specification of postcondition
assert ((snap(_1)) == (snap(_2)))
```
This is wrong because both `_1` and `_2` should be wrapped in `old`.

**Comment by Aurel300** [comment]
How are you testing this? Current `master` reports a fold/unfold error for me when trying to run that program.

**Comment by vakaras** [comment]
> How are you testing this? Current `master` reports a fold/unfold error for me when trying to run that program.

Sorry, I forgot to mention the user-facing error message. The fold-unfold algorithm fails because `old` is missing.
