### ISSUE TITLE
Possibility of verifying SYCL?

### ISSUE THREAD

**Issue by jon-chuang** [viperproject/prusti-dev#6]
Is it possible the project may be extended to SYCL, the cross-platform parallel language standard (Khronos group) that is now being supported as flagship product by Intel through [OneAPI](https://www.youtube.com/watch?v=EtHCbKuivBA&t=1447s) and also has support throughout industry?

(for instance SYCL is integrated with full support as a [backend to tensorflow](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/common_runtime/sycl), Xilinx is working on it too)

I ask because there seems to be an active attempt to verify "parallel and concurrent software" in [vercors](https://github.com/utwente-fmt/vercors)

Are there any particular reasons why Viper IR would be particularly suited to this task compared to other available options?

**Comment by vakaras** [comment]
Hello @jon-chuang,
If I understand you correctly, you are asking not about Prusti (a verifier for the Rust programming language), but about Viper (a general verification infrastructure for parallel and heap manipulating imperative programs).

I am not aware of anyone trying to create a Viper front-end for SYCL, but also do not see a reason why this could not be done. The core advantages of Viper is that it has native support for primitives that allow modelling concurrent software and good automation via SMT.

**Comment by fpoli** [comment]
Closing as not Prusti-related. Feel free to contact our group (https://www.pm.inf.ethz.ch/) for Viper-related questions!

**Comment by zgrannan** [comment]
Queued af81fb112531dded899545c5f28300fb7e50d8cd with parent f5ab531c4ba3394a283dee9913d1c318b03fd3a6, future [comparison URL](http://34.228.27.164:2346/compare.html?start=f5ab531c4ba3394a283dee9913d1c318b03fd3a6&end=af81fb112531dded899545c5f28300fb7e50d8cd).
