### ISSUE TITLE
Failing test on the top-20 crates

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#68]
The test that runs Prusti on the top-20 crates (see [here](https://github.com/viperproject/prusti-dev/runs/784731462?check_suite_focus=true)) recently started failing.

Probably, the whitelist produced by `cargo-filter` and consumed by Prusti is no longer stable between compiler runs. One option is to skip unsupported functions on the fly while running Prusti, without relying on the on-disk whitelist.

**Comment by fpoli** [comment]
PR #69 should fix the issue with the whitelist. However, on the crates `017_thread_local` and `018_time` there are still errors due to the code generated for type-checking the specifications. Grepping "error" from the log:
```
error[E0118]: no base type found for inherent implementation
error[E0118]: no base type found for inherent implementation
error[E0412]: cannot find type `TzReset` in this scope
error[E0592]: duplicate definitions with name `SteadyTime__PartialOrd__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Add__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Sub__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Ord__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Clone__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Eq__spec`
error[E0592]: duplicate definitions with name `SteadyTime__fmt_Debug__spec`
error[E0592]: duplicate definitions with name `SteadyTime__PartialEq__spec`
error[E0592]: duplicate definitions with name `Timespec__Sub__spec`
error[E0592]: duplicate definitions with name `SteadyTime__PartialOrd__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Add__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Sub__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Ord__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Clone__spec`
error[E0592]: duplicate definitions with name `SteadyTime__Eq__spec`
error[E0592]: duplicate definitions with name `SteadyTime__fmt_Debug__spec`
error[E0592]: duplicate definitions with name `SteadyTime__PartialEq__spec`
error[E0592]: duplicate definitions with name `Tm__Sub__spec`
```

@jakobbeckmann Would it be easy to avoid generating code for type-checking when the source code does not use Prusti attributes?

**Comment by f4z3r** [comment]
> PR #69 should fix the issue with the whitelist. However, on the crates `017_thread_local` and `018_time` there are still errors due to the code generated for type-checking the specifications. Grepping "error" from the log:
> 
> ```
> error[E0118]: no base type found for inherent implementation
> error[E0118]: no base type found for inherent implementation
> error[E0412]: cannot find type `TzReset` in this scope
> error[E0592]: duplicate definitions with name `SteadyTime__PartialOrd__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Add__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Sub__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Ord__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Clone__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Eq__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__fmt_Debug__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__PartialEq__spec`
> error[E0592]: duplicate definitions with name `Timespec__Sub__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__PartialOrd__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Add__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Sub__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Ord__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Clone__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__Eq__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__fmt_Debug__spec`
> error[E0592]: duplicate definitions with name `SteadyTime__PartialEq__spec`
> error[E0592]: duplicate definitions with name `Tm__Sub__spec`
> ```
> 
> @jakobbeckmann Would it be easy to avoid generating code for type-checking when the source code does not use Prusti attributes?

@fpoli Yes I will have a look at it. Should be rather trivial.

**Comment by fpoli** [comment]
Thanks!
