### ISSUE TITLE
Using old(struct) in predicate arguments

### ISSUE THREAD

**Issue by enjhnsn2** [viperproject/prusti-dev#681]
Hey, 
I'm trying to define a predicate that enforces that a data structure has been safely updated by comparing the old and new versions of the structure, but I'm getting some verification errors. 
For example, if I have a struct Point:
```
struct Point {
    pub x: u32, 
    pub y: u32, 
}
```
I can define a function that updates it and a contract to ensure it was updated properly, like so:
```
#[ensures(old(point.x) + 1 == point.x && old(point.y) + 1 == point.y)]
fn diagonal_shift(point: &mut Point){
    point.x += 1;
    point.y += 1;
}
```
However, if the data structure and its invariants were more complex, I would want to encapsulate the safety invariant in a predicate like so:
```
predicate! {
    fn safely_translated(old_point: &Point, point: &Point) -> bool {
        old_point.x + 1 == point.x && 
        old_point.y + 1 == point.y
    }
}

#[ensures(safely_translated(old(point), point))]
fn diagonal_shift(point: &mut Point){
    point.x += 1;
    point.y += 1;
}
```
However, this causes the error `[Prusti: invalid specification] the type of the old expression is invalid`

So, a few questions:
Is there any standard way to cleanly encapsulate step-wise data structure invariants like this?
I don't really know how `old` interacts with struct field accesses, but would it be difficult to implement the ability to pass the old and new struct to a predicate like this? If not, I would be willing to implement it if you could give me a pointers. 
If it is difficult / fundamentally conflicts with how viper handles structures, do you know of any workaround that is more clean then just reproducing whole set of step-wise in invariants at every function that enforces them?

**Comment by vakaras** [comment]
Hello! When the error message was added, Prusti used an encoding of specifications that did not support two-state predicates. However, we changed the encoding since then and it might be enough to just relax the validation step. You could try commenting out the validation and see what happens.

**Comment by enjhnsn2** [comment]
Awesome, I removed https://github.com/viperproject/prusti-dev/blob/f10c42edd3d60480b458d1af22516667c0048072/prusti-viper/src/encoder/pure_function_encoder.rs#L813-L818 and it works fine, thanks!
