### ISSUE TITLE
Consistency error: Local variable _0 not found.

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#693]
There seems to be a problem when calling a pure method on a type which is returned from a pure method/function.

Here are three examples that replicate the issue. It seems to be happening with both primitive return types and arbitrary `Copy` return types as the second return type in the call chain in the function body of `fn test()`.

# Example 1
```rust
#[derive(Clone, Copy)]
pub struct A;

impl A {
    #[pure]
    pub fn get(&self) -> A {
        A
    }
}

#[pure]
pub fn test(a: A) -> A {
    a.get().get()
}
```

Error message:

```
error: [Prusti internal error] consistency error in test: Consistency error: Local variable _0 not found. (@0.0)

error: [Prusti internal error] consistency error in test: Consistency error: Type of function body must match function type. (<no position>)

error: could not compile `example` due to 2 previous errors
Command exited with non-zero status 101
```

# Example 2
```rust
#[derive(Clone, Copy)]
pub struct A;

impl A {
    #[pure]
    pub fn get(&self) -> A {
        A
    }

    #[pure]
    pub fn len(&self) -> usize {
        0
    }
}

#[pure]
pub fn test(a: A) -> usize {
    a.get().len()
}
```

Error message: 

```quote
error: [Prusti internal error] consistency error in test: Consistency error: Local variable _0 not found. (@0.0)

error: [Prusti internal error] consistency error in test: Consistency error: Type of function body must match function type. (<no position>)
```

# Example 3
```rust
#[derive(Clone, Copy)]
pub struct A;

impl A {
    #[pure]
    pub fn len(&self) -> usize {
        0
    }
}

#[pure]
pub fn a() -> A {
    A
}

#[pure]
pub fn test() -> usize {
    a().len()
}
```

Error message:

```
error: [Prusti internal error] consistency error in test: Consistency error: Local variable _0 not found. (@0.0)

error: [Prusti internal error] consistency error in test: Consistency error: Type of function body must match function type. (<no position>)
```

# Example 4
```rust
#[derive(Clone, Copy)]
pub struct A(usize);

impl A {
    #[pure]
    pub fn len(&self) -> usize {
        0
    }
}

#[pure]
pub fn a() -> A {
    A(0)
}

#[pure]
pub fn test() -> usize {
    a().len()
}
```

Error message:

```
error: [Prusti internal error] consistency error in test: Consistency error: Local variable _0 not found. (@0.0)

error: [Prusti internal error] consistency error in test: Consistency error: Type of function body must match function type. (<no position>)
```

**Comment by Pointerbender** [comment]
I did a little more digging to see if I can find more background information that might help. I haven't found any good solution yet, but here is what I found out.

When compiling example 3 from the original post, the Viper program for the Rust function `fn test()` looks like this (some parts omitted):

```
     ...

    function m_a__$TY$__UnitDomain(): UnitDomain
      requires true
      requires true
      ensures true
      ensures [result == mirror_simple$m_a__$TY$__UnitDomain(), true]
    {
      _0  <--- This line triggers the consistency error
    }
    
    function m_len__$TY$__UnitDomain$$int$(_1: UnitDomain): Int
      requires true
      requires true
      ensures true
      ensures 0 <= result
      ensures result <= 18446744073709551615
      ensures [result == mirror_simple$m_len__$TY$__UnitDomain$$int$(_1), true]
    {
      0
    }

   method m_test() returns (_0: Ref)
    {
        ....
    }

     ...
```

In the Prusti debug logs it shows the following relevant ("trace" level, timestamps removed for readability and emphasis mine):

```markdown
**[DEBUG prusti_viper::encoder::pure_functions::encoder] Encode pure function m_a**
[TRACE prusti_viper::encoder::mir_interpreter] States before: {}
[TRACE prusti_viper::encoder::mir_interpreter] Apply terminator Terminator { source_info: SourceInfo { span: src/lib.rs:16:2: 16:2 (#0), scope: scope[0] }, kind: return }
[TRACE prusti_viper::encoder::pure_functions::interpreter] apply_terminator Terminator { source_info: SourceInfo { span: src/lib.rs:16:2: 16:2 (#0), scope: scope[0] }, kind: return }, states: {}
**[TRACE prusti_viper::encoder::pure_functions::interpreter] Return type: A**
[TRACE prusti_viper::encoder::mir_interpreter] State after: MultiExprBackwardInterpreterState { exprs: [Local(Local { variable: _0: Ref(m_A$_beg_$_end_), position: Position { line: 0, column: 0, id: 0 } })], substs: {} }
[TRACE prusti_viper::encoder::mir_interpreter] State before: MultiExprBackwardInterpreterState { exprs: [Local(Local { variable: _0: Ref(m_A$_beg_$_end_), position: Position { line: 0, column: 0, id: 0 } })], substs: {} }
[TRACE prusti_viper::encoder::mir_interpreter] Apply statement1 _0 = A
[TRACE prusti_viper::encoder::pure_functions::interpreter] apply_statement _0 = A, state: exprs=_0,
[TRACE prusti_viper::encoder::mir_encoder] Encode place _0
[TRACE prusti_viper::encoder::mir_encoder] Encode projection _0, []
[TRACE prusti_viper::encoder::mir_interpreter] use_place Local(Local { variable: _0: Ref(m_A$_beg_$_end_), position: Position { line: 0, column: 0, id: 0 } })
[DEBUG prusti_viper::encoder::pure_functions::interpreter] Encode aggregate Adt(A, 0, [], None, None), []
[TRACE prusti_viper::encoder::mir_interpreter] State after: MultiExprBackwardInterpreterState { exprs: [Local(Local { variable: _0: Ref(m_A$_beg_$_end_), position: Position { line: 0, column: 0, id: 0 } })], substs: {} }
**[DEBUG prusti_viper::encoder::pure_functions::encoder] Pure function m_a has been encoded with expr: _0**
[DEBUG prusti_viper::encoder::name_interner] Interning of "m_prusti_example$$a" is "m_a"
**[DEBUG prusti_viper::encoder::pure_functions::encoder] Encode pure function m_a given body Some(_0)**
[TRACE prusti_viper::encoder::borrows] [compute_borrow_infos] enter name=DefId(0:11 ~ prusti_example[76c6]::a)
[TRACE prusti_viper::utils::type_visitor] visit_ty(A)
[TRACE prusti_viper::utils::type_visitor] visit_sty(Adt(A, []))
[TRACE prusti_viper::utils::type_visitor] visit_adt(A)
[TRACE prusti_viper::utils::type_visitor] visit_adt_variant(VariantDef { def_id: DefId(0:5 ~ prusti_example[76c6]::A), ctor_def_id: Some(DefId(0:6 ~ prusti_example[76c6]::A::{constructor#0})), ident: A#0, discr: Relative(0), fields: [], ctor_kind: Const, flags: NO_VARIANT_FLAGS })
[TRACE prusti_viper::encoder::borrows] [compute_borrow_infos] exit result=ProcedureContract {
    IN:
    OUT:
    MAGIC:
    }
    
**[DEBUG prusti_viper::encoder::pure_functions::encoder] encoded_return: _0: Domain(UnitDomain)**
[DEBUG prusti_viper::encoder::errors::error_manager] Register position 21 at span MultiSpan { primary_spans: [src/lib.rs:14:1: 16:2 (#0)], span_labels: [] }
[DEBUG prusti_viper::encoder::errors::error_manager] Register error at: 21
[DEBUG prusti_viper::encoder::errors::error_manager] Register position 22 at span MultiSpan { primary_spans: [src/lib.rs:14:1: 16:2 (#0)], span_labels: [] }
[DEBUG prusti_viper::encoder::errors::error_manager] Register error at: 22
[TRACE prusti_common::vir::optimizations::functions::simplifier] [enter] simplify = function m_a(): Domain(UnitDomain)
      requires true
      requires true
      ensures true
    {
        _0
    }
[TRACE prusti_common::vir::optimizations::functions::simplifier] [enter] apply_rules=_0
[TRACE prusti_common::vir::optimizations::functions::simplifier] [exit] apply_rules=_0
[TRACE prusti_common::vir::optimizations::functions::simplifier] [exit] simplify = function m_a(): Domain(UnitDomain)
      requires true
      requires true
      ensures true
    {
        _0
    }
[DEBUG prusti_viper::encoder::snapshot::encoder] [snap] function: "m_a"
[DEBUG prusti_viper::encoder::snapshot::encoder] [snap] function: "m_a"
**[TRACE prusti_viper::encoder::pure_functions::interface] [exit] encode_pure_function_def(DefId(0:11 ~ prusti_example[76c6]::a))**
```

It looks like somewhere between `[TRACE prusti_viper::encoder::pure_functions::interpreter] Return type: A` and `[DEBUG prusti_viper::encoder::pure_functions::encoder] Pure function m_a has been encoded with expr: _0` the return type `A` is turned into a Viper function body expression `_0`, but this variable does not exist within the pure function. The Viper function body for the corresponding Rust function `pub fn a() -> A` should probably hold something else (I haven't found out what should be there, though).

As a work-around, I tried added a `#[trusted]` annotation to `pub fn a() -> A`, so that it would be rendered as an abstract Viper function (and omit the `{ _0 }` which causes the consistency error). But unfortunately, this gives a different error:

```
error: [Prusti internal error] consistency error in test: Consistency error: expected the same type, but got Ref and Snap$m_A$_beg_$_end_ (@0.0)
```

(after pulling the latest commit from the master branch, this error does no longer show up for unit structs, but I can still trigger it when the struct `A` has any field, e.g. `pub struct A(usize)`).

I hope this helps, please let me know if I can help somehow by investigating other parts :smile:

**Comment by vakaras** [comment]
Thanks for looking into this! The type `UnitDomain` in Viper corresponds to Rust's `()`, so something is deeply broken here.

**Comment by Pointerbender** [comment]
@vakaras Thanks for that extra information. Initially, I thought it was not that far-fetched that `pub struct A;` from example 3 is represented as Rust's `()` within Viper, because `pub struct A;` is a unit struct (i.e. no fields). However, thanks to your remark, I realized that this should not happen in this stage of MIR to Viper (pure function) encoding. I have a couple of questions, to which the answers could help me investigate this further:

* Would a Rust `pub struct A;` ever be encoded to a `()` (or `UnitDomain`) inside a Viper program? For example, might this happen during the simplification step within the pure function encoding (which happens later, after the Viper function body is generated in the logs of my previous comment)? If not, what return type would we expect for `pub struct A;` w.r.t. the Viper function `function m_len*` inside a definitive Viper program for `pub fn test() -> usize`?
* In the Viper program for `#[pure] pub fn test() -> usize {}` in example 3 and 4 (I just edited the original post to add example 4), what is the Viper function for `#[pure] pub fn a() -> A {}` expected to look like, including the Viper function body?
* I understood on Zulip that this might have been working before. Is there a known Prusti version or git commit where this was working before? I might be able to learn more about the changes that caused the regression by doing a diff between the latest commit on the master branch and the last known working version.

I have some time this Friday and Saturday to dive deeper into this :smile: If I can compare what it's currently doing to what is expected, I might be able to find out more relevant details. Thanks!

**Comment by vakaras** [comment]
@Pointerbender Thank you for looking into this!

> Would a Rust `pub struct A;` ever be encoded to a `()` (or `UnitDomain`) inside a Viper program?

No. It should always be `A` + some mangling. 

> If not, what return type would we expect for `pub struct A;` w.r.t. the Viper function `function m_len*` inside a definitive Viper program for `pub fn test() -> usize`?

It should be `Snap$A` (the non-primitive types in pure functions are `Snap$` + original Rust type name).

> In the Viper program for `#[pure] pub fn test() -> usize {}` in example 3 and 4 (I just edited the original post to add example 4), what is the Viper function for `#[pure] pub fn a() -> A {}` expected to look like, including the Viper function body?

Not sure if you saw my last PRs, but I am basically rewriting that part of the code now and this will change soon. I think the core of the problem is that the type `A` gets lost somehow in the translation body. If we knew at which point exactly that happens, I think I could fix this bug as part of the changes I am doing. My current guess is that the problem is with `mir_interpreter` because this line `[DEBUG prusti_viper::encoder::pure_functions::encoder] Pure function m_a has been encoded with expr: _0` looks already wrong. (The result should not be `_0`.)

**Comment by Aurel300** [comment]
Assuming the snapshot encoder has not changed significantly since I last worked on it, then the snapshot of `A` can indeed be `UnitDomain` if `A` has no fields.

**Comment by vakaras** [comment]
> Assuming the snapshot encoder has not changed significantly since I last worked on it, then the snapshot of `A` can indeed be `UnitDomain` if `A` has no fields.

Thanks for pointing this out! I was not aware of that. @Pointerbender The snapshot encoder has not been changed (yet).

**Comment by Pointerbender** [comment]
Thank you for the pointers! :smile:

Currently I'm looking at the method `PureFunctionEncoder::encode_function(&self)` in `prusti-viper/src/encoder/mir/pure_functions/encoder.rs`. This method performs some state mutations, however, from the beginning to the end of this method the state remains unchanged. It's value is:

```
MultiExprBackwardInterpreterState {
   exprs: [Local(Local {
      variable: _0: Ref(m_A$_beg_$_end_),
      position: Position { line: 0, column: 0, id: 0 }
   })],
   substs: {}
}
```

The embedded expression is also the pure function body, for which the `Display` trait outputs `_0`.

The interesting part of `encode_function()` is:

```rust
    pub fn encode_function(&self) -> SpannedEncodingResult<vir::Function> {
        // .... --- SNIPPED ---
        let mut body_expr = state.into_expressions().remove(0);
        debug!(
            "Pure function {} has been encoded with expr: {}",
            function_name, body_expr
        );

        // if the function returns a snapshot, we take a snapshot of the body
        if self.encode_function_return_type()?.is_snapshot() {
            let ty = self
                .encoder
                .resolve_typaram(self.mir.return_ty(), self.tymap);
            let return_span = self.get_local_span(mir::RETURN_PLACE);

            if !self.encoder.env().type_is_copy(ty) {
                return Err(SpannedEncodingError::unsupported(
                    "return type of pure function does not implement Copy",
                    return_span,
                ));
            }

            body_expr = vir::Expr::snap_app(body_expr);
        }

        self.encode_function_given_body(Some(body_expr))
   }
```

Here, `self.encode_function_return_type()?` returns a `Domain(DomainType { label: "UnitDomain", arguments: [], variant: "" })`, for which `is_snapshot()` returns `false`. I guess this is correct for the Rust type `()`, which is a built-in primitive, but it is not true for `pub struct A` which is a custom ADT. Therefore, the snap encoding for `A` is never invoked, and the `_0` variable is left untouched before passing it to the Viper program. This seems contradictory, because it is checking if its already a snap return type, before proceeding to encode it as snap again. I think we find the bug at this line, because if we replace:

```rust
if self.encode_function_return_type()?.is_snapshot() {
```

with

```rust
if self.encode_function_return_type()?.is_domain() {
```

Then examples 1 & 2 & 3 are verified okay and the output for `#[pure] pub fn a()` in the Viper program for `pub fn test()` shows:

```
    function m_a__$TY$__UnitDomain(): UnitDomain
      requires true
      requires true
      ensures true
      ensures [result == mirror_simple$m_a__$TY$__UnitDomain(), true]
    {
      unit$__$TY$__UnitDomain()
    }
```

However, example 4 still fails to compile for the same reason as before :smile: I'm still looking into this one!

**Comment by Aurel300** [comment]
`is_domain` instead of `is_snapshot` might be correct in many cases… We don't use domains (or rather values of a domain type) for anything besides snapshots AFAIK.

**Comment by Pointerbender** [comment]
It may need to check for both `is_domain` and `is_snapshot`. I just found out that a return type for `pub struct A(usize)` is not seen as a domain, but it is correctly recognized as a snapshot. However, when verifying example 4 with the patch:

```rust
let encoded_return_type = self.encode_function_return_type()?;
if encoded_return_type.is_snapshot() || encoded_return_type.is_domain() {
```

The Viper program and error logs show:

```
    function m_a__$TY$__Snap$m_A$_beg_$_end_(): Snap$m_A$_beg_$_end_
      requires true
      requires true
      ensures true
      ensures [result == mirror_simple$m_a__$TY$__Snap$m_A$_beg_$_end_(), true]
    {
      snap$__$TY$__m_A$_beg_$_end_$Snap$m_A$_beg_$_end_(_0)
    }

    function snap$__$TY$__m_A$_beg_$_end_$Snap$m_A$_beg_$_end_(self: Ref): Snap$m_A$_beg_$_end_
      requires acc(m_A$_beg_$_end_(self), read$())
    {
      (unfolding acc(m_A$_beg_$_end_(self), read$()) in (unfolding acc(usize(self.f$0), read$()) in cons$0$__$TY$__$int$$Snap$m_A$_beg_$_end_(self.f$0.val_int)))
    }


error: [Prusti internal error] consistency error in test: Consistency error: Local variable _0 not found. (@0.0)

error: [Prusti internal error] consistency error in test: Consistency error: expected the same type, but got Ref and Snap$m_A$_beg_$_end_ (@0.0)
```

Something seems off when passing `_0` to function `snap$__$TY$__m_A$_beg_$_end_$Snap$m_A$_beg_$_end_`. I'm not sure what to make of it yet :smile: ~My next idea is to try and see if I can replace `_0` with a call to `builtin$havoc_ref()` instead and see if that makes it better.~ Scratch that, `builtin$havoc_ref()` is a method and it's not possible to call methods from (pure) functions!

**Comment by vakaras** [comment]
The MIR for function `a` in example 4 is as follows:
```
// MIR for `a` 0 renumber

fn a() -> A {
    let mut _0: A;                       // return place in scope 0 at prusti-tests/tests/verify_overflow/pass/issues/issue-693.rs:14:15: 14:16

    bb0: {
        _0 = A(const 0_usize);           // scope 0 at prusti-tests/tests/verify_overflow/pass/issues/issue-693.rs:15:5: 15:9
        return;                          // scope 0 at prusti-tests/tests/verify_overflow/pass/issues/issue-693.rs:16:2: 16:2
    }
}
```
it should be encoded to something like this:
```
function m_a__$TY$__Snap$m_A$_beg_$_end_(): Snap$m_A$_beg_$_end_
  requires true
  requires true
  ensures true
  ensures [result == mirror_simple$m_a__$TY$__Snap$m_A$_beg_$_end_(), true]
{
  cons$0$__$TY$__$int$$Snap$m_A$_beg_$_end_(0)
}
```

I suspect that the problem is that the MIR backward interpreter fails to properly handle `_0 = A(const 0_usize);` (also, I think we are missing a check that all local variables used inside a pure function should be `Copy`). In other words, after `let mut body_expr = state.into_expressions().remove(0);` the `body_expr` variable should contain something else than `_0`.

**Comment by Pointerbender** [comment]
Thanks @vakaras! Which command do you use to view the MIR? When I run `cargo rustc -- -Z unpretty=mir` or `prusti-rustc -Z unpretty=mir src/lib.rs` I get a slightly different output:

```
fn a() -> A {
    let mut _0: A;                       // return place in scope 0 at src/lib.rs:36:15: 36:16

    bb0: {
        (_0.0: usize) = const 0_usize;   // scope 0 at src/lib.rs:37:5: 37:9
        return;                          // scope 0 at src/lib.rs:38:2: 38:2
    }
}
```

However, when adding trace logs for the `mir` argument inside `run_backward_interpretation()` I can also see the `_0 = A(const 0_usize);` statement, just like in the MIR you posted. I think I might not be using the correct command to view the MIR (also I'm on the `nightly-2021-09-20-x86_64-unknown-linux-gnu` toolchain, in case the output format changed between toolchain versions).

**Comment by Pointerbender** [comment]
> I suspect that the problem is that the MIR backward interpreter fails to properly handle `_0 = A(const 0_usize);`

My further investigation confirms your suspicion :smile: The relevant code is in `prusti-viper/src/encoder/mir/pure_functions/interpreter.rs`:

```rust
    fn apply_statement(
        &self,
        bb: mir::BasicBlock,
        stmt_index: usize,
        stmt: &mir::Statement<'tcx>,
        state: &mut Self::State,
    ) -> Result<(), Self::Error> {
...
        match stmt.kind {
...
            mir::StatementKind::Assign(box (ref lhs, ref rhs)) => {
...
                match rhs {
...
                            &mir::AggregateKind::Adt(adt_def, variant_index, subst, _, _) => {
...
                                    match encoded_operand {
                                        Some(encoded_rhs) => {
                                            // Substitute a place
                                            state.substitute_place(&field_place, encoded_rhs);
                                        }
                                        None => {
                                            // Substitute a place of a value with an expression
                                            let rhs_expr =
                                                self.mir_encoder.encode_operand_expr(operand)
                                                    .with_span(span)?;
                                            state.substitute_value(
                                                &self.encoder.encode_value_expr(field_place, field_ty).with_span(span)?,
                                                rhs_expr,
                                            );
                                        }
                                    }
...
```

Here it ends up in the most inner branch for `None => {}` when applying the statement `_0 = A(const 0_usize)` (here `rhs_expr` is `Const(ConstExpr { value: BigInt("0"), position: Position { line: 0, column: 0, id: 0 } })`). The state before the statement is applied and the state after are identical: `MultiExprBackwardInterpreterState { exprs: [Local(Local { variable: _0: Ref(m_A$_beg_$_end_), position: Position { line: 0, column: 0, id: 0 } })], substs: {} }`. The TypedRef for the inner Local is `TypedRef(TypedRef { label: "adt$m_A", arguments: [], variant: "" })`, where we can see it is missing its constructor argument (`const 0_usize`) because `arguments` is empty. It should probably show an `Expr::Const(ConstExpr { value: Const::BigInt("0"), position: Position::default() })` in its `arguments` list after the statement is applied to the current state, so that it can be matched to the `cons$0$__$TY$__$int$$Snap$m_A$_beg_$_end_` Viper function during the snap encoding step.

**Comment by vakaras** [comment]
> Thanks @vakaras! Which command do you use to view the MIR? When I run `cargo rustc -- -Z unpretty=mir` or `prusti-rustc -Z unpretty=mir src/lib.rs` I get a slightly different output:

Setting the environment variable `PRUSTI_DUMP_DEBUG_INFO=true` will cause Prusti to create `log/mir/` directory. `renumber` is the version of MIR used by Prusti.

**Comment by vakaras** [comment]
> > I suspect that the problem is that the MIR backward interpreter fails to properly handle `_0 = A(const 0_usize);`
> 
> My further investigation confirms your suspicion smile The relevant code is in `prusti-viper/src/encoder/mir/pure_functions/interpreter.rs`:

So, it seems to me that the code for handling the creation of aggregates is completely missing. @fpoli since you wrote the interpreter, do you remember what needs to be done to enable that?

The interpreter state is `_0` and the substitution that `apply_statement` tries to apply is `_0.f$0.val_int → 0`, which obviously fails. I guess that to fix this, we need to check whether we have the `lhs` in our state and expand it so that the substitution can be applied?

**Comment by fpoli** [comment]
I think something broke when the interpreter had to be patched to work with snaphshots. I'll check.

**Comment by fpoli** [comment]
For example 3 I think the cause is that this loop never gets executed because an empty struct has no fields: https://github.com/viperproject/prusti-dev/blob/c750bbf4a19260050cc81925e0c0605fe17f958a/prusti-viper/src/encoder/mir/pure_functions/interpreter.rs#L848 The whole loop could be replaced with the construction of a single snapshot.

**Comment by Pointerbender** [comment]
Thank you for the fix @fpoli! Works like a charm! :smile:

**Comment by fpoli** [comment]
You are welcome :) There are still some leftovers, like https://github.com/viperproject/prusti-dev/issues/714.

**Comment by Aurel300** [comment]
We still get this error with a pure function with no return (= empty tuple).

```rs
#[pure]
fn foo(a: bool, b: bool) {}
```

```
function m_foo__$TY$__$bool$$$bool$$Snap$tuple0$(_1: Bool, _2: Bool): Snap$tuple0$
  ensures [result == mirror_simple$m_foo__$TY$__$bool$$$bool$$Snap$tuple0$(_1, _2), true]
{
  snap$__$TY$__tuple0$$Snap$tuple0$(_0)
}
```

**Comment by fpoli** [comment]
It's probably because the returned empty tuple is represented in MIR with a `mir::Rvalue::Use(mir::Operand::Constant(..))`, not with `mir::Rvalue::Aggregate(..)`.

The following works fine because it generates a `mir::Rvalue::Aggregate(..)`.
```rust
#[pure]
fn foo(a: bool, b: bool) { () }
```
