### ISSUE TITLE
Consistency error: expected the same type, but got Ref and Snap$m_A$_beg_$_end_ (@0.0)

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#707]
Hi :wave: I've ran into a different consistency error, which may or may not be related to #693. There are a couple of differences between this case and #693:

1. The error message is different: `Consistency error: expected the same type, but got Ref and Snap$m_A$_beg_$_end_ (@0.0)`
2. In the below example, the consistency error appears when calling a pure function from a non-pure function (#693 is about calling a pure function from a pure function).

An annotated example that reproduces the error message is as follows:

```rust
use prusti_contracts::*;

#[derive(Clone,Copy)]
pub struct A {
    _inner: usize,
}

#[derive(Clone,Copy)]
pub struct B {
    inner: A,
}

impl B {
    #[pure] // <-- removing this attribute makes the below error go away
    // #[trusted] // <-- adding this attribute doesn't help
    pub fn get(&self) -> A {
        self.inner
    }
}

// This method triggers the Prusti error:
// "error: [Prusti internal error] consistency error in test: Consistency error:
// expected the same type, but got Ref and Snap$m_A$_beg_$_end_ (@0.0)"
// The error only shows up when returning an ADT, there is no error when
// the return type is a primitive.
pub fn test(b: &B) -> A {
    b.get()
}
```

The reason I think it might be related, is because it looks like it's also tripping over the snapshot encoding of `A` (`Snap$m_A$_beg_$_end_`), which is similar to #693, even though the error message is different.

I'll try to see if I can narrow down where this is coming from in the Viper program and report back!

**Comment by vakaras** [comment]
I think I know what is going on here: the encoding of `b.get()` tries to store the result in a heap-allocated memory while `get` returns a purified version. In other words, the current encoding is:
```
result := B$get()
```
and it should be:
```
assume snap(result) == B$get()
```

**Comment by Pointerbender** [comment]
If I open the resulting Viper program with Viper IDE, then it tells me that the error is on this line:

```
inhale _0 == m_get__$TY$__Snap$m_B$_beg_$_end_$Snap$m_A$_beg_$_end_(snap$__$TY$__m_B$_beg_$_end_$Snap$m_B$_beg_$_end_(_2.val_ref))
```

Following what @vakaras said, changing it to this line makes the program verify okay in Viper:

```
inhale snap$__$TY$__m_A$_beg_$_end_$Snap$m_A$_beg_$_end_(_0) == m_get__$TY$__Snap$m_B$_beg_$_end_$Snap$m_A$_beg_$_end_(snap$__$TY$__m_B$_beg_$_end_$Snap$m_B$_beg_$_end_(_2.val_ref))
```

**Comment by Pointerbender** [comment]
Thank you for the lightning fast fix @vakaras ! I've found another one related to array (pure) lookups, will post it shortly as a new issue :smile:
