### ISSUE TITLE
Use FxHashSet/FxHashMap

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#711]
Prusti uses collections such as `HashSet` and `HashMap`, which use a high quality hasher that provides high protection against collisions. However, that hasher is relatively slow and we don't care about HashDoS attacks. So, replacing those collections with `FxHashSet` and `FxHashMap` should always be better.

Collections: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fx/index.html

See also: https://nnethercote.github.io/perf-book/hashing.html

**Comment by teymour-aldridge** [comment]
I'd like to work on this (probably over the weekend).

**Comment by fpoli** [comment]
Great! :) Feel free to ask any questions here or on Zulip. I would suggest to not change more than one module at a time, to keep the PRs small. [This script](https://github.com/viperproject/prusti-dev/blob/master/design/src/dependency_graph.py) (if it still works) can be used to visualize the dependencies between the modules.
