### ISSUE TITLE
Unhandled verification error when using slices

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#718]
The following regression test fails to verify with `prusti-rustc`, but when running `x.py test` the compilation succeeds.

```rust
#![no_std]
extern crate prusti_contracts;
use prusti_contracts::*;

#[derive(Clone, Copy)]
pub struct A {
    _inner: usize
}
pub struct B {
    inner: [A]
}

impl B {
    /// Obtain the length of a slice.
    #[pure]
    pub const fn len(&self) -> usize { //~ ERROR unhandled verification error
        self.inner.len()
    }
}

pub fn test(b: &mut B) -> usize {
    b.len()
}

pub fn main() {}
```

The output of `prusti-rustc` is (slightly reformatted to avoid sideways scrolling):

```
$ ./target/debug/prusti-rustc prusti-tests/tests/verify/fail/issues/TBD.rs 
  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 


Verification of 4 items...
error: [Prusti internal error] unhandled verification error: PureFunctionPostconditionValueRangeOfResult 
[postcondition.violated:assertion.false] Postcondition of m_len__$TY$__Snap$struct$m_B$$int$ might not hold.
Assertion result <= 18446744073709551615 might not hold. (@16.5)
  --> prusti-tests/tests/verify/fail/issues/TBD.rs:16:5
   |
16 | /     pub const fn len(&self) -> usize { //~ ERROR unhandled verification error
17 | |         self.inner.len()
18 | |     }
   | |_____^
   |
   = help: This could be caused by too small assertion timeout.
      Try increasing it by setting the configuration parameter ASSERT_TIMEOUT to a larger value.
note: the failing assertion is here
  --> prusti-tests/tests/verify/fail/issues/TBD.rs:16:5
   |
16 | /     pub const fn len(&self) -> usize { //~ ERROR unhandled verification error
17 | |         self.inner.len()
18 | |     }
   | |_____^

Verification failed
error: aborting due to previous error
```

Additionally, the imposed post-condition `result <= 18446744073709551615` in the error message is too liberal (unsound?). `18446744073709551615` is `usize::MAX`, which can never be valid for the length of slice reference. The length of a slice reference should be at most `isize::MAX as usize` bytes. There exists no valid way in Rust to construct slice references with more elements than can fit inside `isize::MAX` bytes (i.e. `len * sizeof(T) <= isize::MAX`), see <https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety>. Note that raw pointers and `NonNull` do allow pointing to slices with more than `isize::MAX` bytes, this is only disallowed for references to slices, because internally the Rust core library performs "inbounds GEP" LLVM instructions on pointers derived from the slice reference, such as the `<*const [T]>::offset`, `<&mut [T]>::add` methods, which are used for slicing/indexing.)

I have 2 regression tests that replicate both these issues. But since `x.py test` is not recognizing the first one, I will open a draft PR for these regression tests (separately from issue #709 where I encountered these two problems when making more regression tests).

<sub>Edit: clarified explanation around maximum slice reference length</sub>

**Comment by vakaras** [comment]
Thank you for reporting this! I think the bound on the returned value is
too liberal because it is coming not from the postcondition of `len`, but
from `usize` bounds. In other words, the problem is that `len` does not
have a postcondition specified. We definitely should fix that.

Regarding the missing verification error: are the tests in the
`verify-overflow` folder? Overflow checking needs to be enabled for the
bound encoding to happen.

**Comment by Pointerbender** [comment]
Just a quick update to summarize the latest activity on this issue: there are now 2 test cases in `prusti-tests/tests/verify_partial/fail/issues` which reproduce the errors mentioned in this issue. Once the underlying cause is fixed, these 2 test cases can be moved to `prusti-tests/tests/verify_overflow/pass/issues` to be re-used as regression tests.

**Comment by fpoli** [comment]
If an array is made of zero-size-types, it seems that its length can be greater than `isize::MAX`. The following fully-safe program compiles and prints `Len: 9223372036854775817`, which is `(isize::MAX as usize) + 10`.

```rust
extern crate static_assertions as sa;

fn main() {
    const SIZE: usize = (isize::MAX as usize) + 10;
    const A: [(); SIZE] = [(); SIZE];
    sa::const_assert!(A.len() == SIZE);
    println!("Len: {}", A.len());
}
```

(The `result <= 18446744073709551615` check comes from the `usize` return type; that's not an unsoundness.)

**Comment by fpoli** [comment]
The unhandled verification error seems an incompleteness in the axiomatization of slices; probably a trigger that is too restrictive. However, it arises from the *pure* encoding of the pure function, not from the impure encoding. @vakaras do we still need to check the postcondition in the pure encoding? I suspect it's redundant.

**Comment by Pointerbender** [comment]
> If an array is made of zero-size-types, it seems that its length can be greater than isize::MAX.

Nice example :) I believe the length invariant of `&[T; N]` should be `N * sizeof(T) <= isize::MAX`, this also holds for `[(); usize::MAX]`. A instance of `&[u8; M]` (`M > isize::MAX`) is unsound (see [`[T]::get`](https://doc.rust-lang.org/src/core/slice/index.rs.html#195-206) and [`[T]::get_unchecked`](https://doc.rust-lang.org/src/core/slice/index.rs.html#218-225), this would violate the safety contracts for `ptr::slice_from_raw_parts` and `<*const T>::add`, which both require that the computed offset fits inside an `isize::MAX`.

Edit: I guess the length invariant could be more clearly expressed in Prusti as:
```rust
impl<T> [T] { // &[T; N] is coerced to &[T] when calling .len() on it
  #[ensures(result * core::mem::size_of::<T>() <= isize::MAX as usize)]
  pub fn len(&self)  -> usize;
}
```

**Comment by fpoli** [comment]
Yes, that postcondition would be more precise. Could you open a separate issue for that? To encode `core::mem::size_of::<T>()` in the contract of `len` we need to obtain the size of a type at compilation time using some [compiler calls](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html).

**Comment by Pointerbender** [comment]
> Could you open a separate issue for that?

Created #733

**Comment by vakaras** [comment]
> The unhandled verification error seems an incompleteness in the axiomatization of slices; probably a trigger that is too restrictive. However, it arises from the _pure_ encoding of the pure function, not from the impure encoding. @vakaras do we still need to check the postcondition in the pure encoding? I suspect it's redundant.

Yes, it is redundant. Eventually, it will be removed.
