### ISSUE TITLE
Update post-condition of `<[T]>::len`

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#733]
The post-condition of `<[T]>::len` should be updated to:

```rust
impl<T> [T] { // &[T; N] is coerced to &[T] when calling .len() on it
  #[ensures(result * core::mem::size_of::<T>() <= isize::MAX as usize)]
  pub fn len(&self)  -> usize;
}
```

This way, the post-condition also holds for `[(); usize::MAX]`, which can safely be constructed. A instance of `&[u8; N]` (where `N > isize::MAX`) is unsound (see [`[T]::get`](https://doc.rust-lang.org/src/core/slice/index.rs.html#195-206) and [`[T]::get_unchecked`](https://doc.rust-lang.org/src/core/slice/index.rs.html#218-225), this would violate the safety contracts for `ptr::slice_from_raw_parts` and `<*const T>::add`, which both require that the computed offset fits inside an `isize::MAX`.

In order to encode `core::mem::size_of::<T>()` in the contract of `len` we need to obtain the size of a type at compilation time using some [compiler calls](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html).

**Comment by JonasAlaif** [comment]
Hmm I can't find the right compiler call to get the size of a type, do send me a message if you know where to find it. As an approximation I have added that `slice.len() <= usize::MAX` for now ([link here](https://github.com/viperproject/prusti-dev/pull/895/files#diff-4a2e939e18c551a3e4ffa38e1ba9dde60dfd23ff788e1b05ad57428ea10cf63bR1291-R1301))

**Comment by Aurel300** [comment]
@JonasAlaif 

- [`TyCtxt::layout_of(ty)`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.layout_of)
- (unwrap/handle error)
- [`.layout`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/struct.TyAndLayout.html#structfield.layout)
- [`.size()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/struct.Layout.html#method.size)
- [`.bytes()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/struct.Size.html#method.bytes) (or `bytes_usize`)

**Comment by JonasAlaif** [comment]
@Aurel300 the funny thing is that now the binary search example [here](https://github.com/viperproject/prusti-dev/pull/901/files#diff-cc26eddd9028ca650016ab53e99a8058ce27dc6a6b4fa7df5aab33bf4d69316dR3) doesn't need this precondition... if we had made it generic then that wouldn't be the case (since with generics we must consider that the size can be 0)
