### ISSUE TITLE
Unexpected panics in `#[pure]` for `Trait`

### ISSUE THREAD

**Issue by LDY1998** [viperproject/prusti-dev#778]
When testing with following spec
```rust
pub trait Max {
    #[pure]
    #[ensures(result >= a && result >= b)]
    #[ensures(result == a || result == b)]
    fn max(a: i32, b: i32) -> i32;
}

struct TestStruct {}

impl Max for TestStruct {
    fn max(a: i32, b: i32) -> i32 {
        if a < b {
            b
        } else {
            a
        }
    }
}


fn main() {
    let x = TestStruct::max(1, 2);
    assert!(x == 2)
}
```
Prusti runs into an unexpected panic when trying to retrieve `BodyWithBorrowckFacts` from `SHARED_STATE`:
```shell
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', prusti-interface/src/environment/mir_storage.rs:47:29
```

**Comment by Aurel300** [comment]
Works now. See [`verify_overflow/pass/trait-contracts-refinement/pure/pure-annotation-gets-inherited.rs`](https://github.com/viperproject/prusti-dev/blob/b152e5a8786fce65dc34990ee50a9050b365f7f9/prusti-tests/tests/verify_overflow/pass/trait-contracts-refinement/pure/pure-annotation-gets-inherited.rs).
