### ISSUE TITLE
Support trait's spec in `extern_spec`

### ISSUE THREAD

**Issue by LDY1998** [viperproject/prusti-dev#779]
Currently, the `extern_spec` attribute reject the specifications attached to a trait's function declaration:
```rust
// This will panics
#[extern_spec]
pub trait Max {
    #[ensures(result >= a && result >= b)]
    #[ensures(result == a || result == b)]
    fn max(a: i32, b: i32) -> i32;
}
```
This is because, in [rewrite](https://github.com/viperproject/prusti-dev/blob/e9a23ebf4d6b364cd9944e197ea906f57e3aaaea/prusti-specs/src/lib.rs#L442), it's only accepting `mod`, `fn` and `impl`. 

Since we might not need to rewrite the trait itself when it's external, simply returning the trait can be one option?

**Comment by vl0w** [comment]
[PR 821](https://github.com/viperproject/prusti-dev/pull/821) adds (experimental) support for external trait specifications.
