### ISSUE TITLE
Inconsistency when generating `function builtin$cast$isize$usize__$TY$__$int$$$int$(number: Int): Int`

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#783]
I've got another fun bug which left me scratching my head for a while :) This one is related to casts from `isize` to `usize`. Typically, these casts appear in a Viper program (when overflow checks are enabled) as:

```
function builtin$cast$isize$usize__$TY$__$int$$$int$(number: Int): Int
  requires -9223372036854775808 <= number
  requires number <= 9223372036854775807
  requires 0 <= number
  requires number <= 18446744073709551615
  ensures 0 <= result
  ensures result <= 18446744073709551615
{
  number
}
```

I've got a Rust project which is relatively large in comparison to the tests in `prusti-tests`, and when I run `cargo-prusti` on it, it generates a Viper program which shows the cast as an abstract function without a function body:

```
function builtin$cast$isize$usize__$TY$__$int$$$int$(number: Int): Int
  requires -9223372036854775808 <= number
  requires number <= 9223372036854775807
  requires 0 <= number
  requires number <= 18446744073709551615
  ensures 0 <= result
  ensures result <= 18446744073709551615
```

So far I have not been able to reproduce this with a minimal example, I can only reproduce it with the larger code base. In the latter case, this causes the verification to fail with error `Postcondition of m_len__$TY$__Snap$struct$m_PageIndex$$int$ might not hold. Assertion Snap$struct$m_PageIndex$0$field$f$entry_count__$TY$__Snap$struct$m_PageIndex$$int$(_1) == -9223372036854775808 ==> result == 0 might not hold.` In this case the only discernible difference is the presence of the function body of `builtin$cast$isize$usize__$TY$__$int$$$int$`. This Rust program creates a successfully verifying Viper program for the `test` method:

```rust
use prusti_contracts::*;

pub struct PageIndex {
    entry_count: isize,
}

impl PageIndex {
    #[pure]
    #[ensures(self.entry_count == isize::MIN ==> result == 0)]
    #[ensures(self.entry_count == 0 ==> result == 0)]
    #[ensures(result <= isize::MAX as usize)]
    pub const fn len(&self) -> usize {
        if self.entry_count < 0 {
            ((1_isize + self.entry_count) + isize::MAX) as usize
        } else {
            self.entry_count as usize
            
        }
    }

    #[pure]
    #[ensures(result == (self.len() == 0))]
    pub const fn is_empty(&self) -> bool {
        self.entry_count == isize::MIN || self.entry_count == 0
    }

    #[requires(self.is_empty())]
    pub fn test(&self) {
        assert!(self.is_empty());
    }
}

pub fn main() {}
```

If you manually edit the resulting Viper program to remove the `{ number }` function body of `builtin$cast$isize$usize__$TY$__$int$$$int$`, then you arrive at the same error as mentioned above (there is a second cascading error `Postcondition of m_is_empty__$TY$__Snap$struct$m_PageIndex$$bool$ might not hold. Assertion result == (m_len__$TY$__Snap$struct$m_PageIndex$$int$(_1) == 0) might not hold.`, too).

Looking at the code that encodes the number casts, it does set a `Some(_)` in its `body` on line 563:

https://github.com/viperproject/prusti-dev/blob/7e3cb69fe1348beeb652101ca6b80eb9548b8c0c/prusti-viper/src/encoder/encoder.rs#L546-L569

so it must be converted into an abstract function somewhere else. One suspect is here on line 209:

https://github.com/viperproject/prusti-dev/blob/7e3cb69fe1348beeb652101ca6b80eb9548b8c0c/prusti-viper/src/encoder/definition_collector.rs#L196-L211

If I update that code to skip any function for which the name starts with `builtin$`, then the errors go away in my code base.

I'm planning to create a PR for this fix, but have some questions that could help me prepare the PR:

* I'm not able to create a minimal reproduction. Might anyone see a way to reproduce this minimally, so that I can add that as a regression test to the PR?
* Is it sound to skip all `builtin$*` functions in the solution? When it arrives there, the `builtin$` function may or may not have a function body (e.g. the [`builtin$unreach*` family](https://github.com/viperproject/prusti-dev/blob/master/prusti-viper/src/encoder/builtin_encoder.rs#L127-L241) are all abstract functions), but if it has one, I believe it should not be purged. Because, somehow this prevents the back-end from following the passed-in variable and it gets stuck during the automated proof.

Thanks!

**Comment by vakaras** [comment]
I think it would be good to have a clear repro and understand it before trying to fix this bug. The definition collector deletes the bodies of functions, which it believes should be unnecessary because doing so improves performance. So, it seems that you found a case showing an insufficiency of definition collector's heuristics. I suspect that the same error could be also triggered with a regular function and that is why I think it would be good to understand this problem better before we just patch it for some class of functions.

The heuristic that is most likely failing here is that it includes the bodies of functions up to some level deep and that level seems to be not deep enough.

**Comment by Pointerbender** [comment]
That sounds good. I'll keep trying to reproduce it somehow by studying the heuristics of the definition collection a bit deeper to see if I can find a counter-example that way :) Thanks for the feedback!

**Comment by vakaras** [comment]
The definition collector keeps the function's body when the function is called explicitly or in its precondition mentions a type that is unfolded (Viper term for accessing a field of that type). Therefore, I think a problematic case would be the one where the function body is needed, but that function is not called directly.

**Comment by vakaras** [comment]
By “called directly” I mean being called in a non-pure function.

**Comment by Pointerbender** [comment]
I managed to create a reproduction. So far I was not able to make it more minimal. The errors from the original post are in the Prusti debug logs of the Viper program for `Cursor::is_valid_path`:

```rust
use prusti_contracts::*;

#[derive(Clone, Copy, PartialEq, Eq)]
pub struct PageIndex {
    entry_count: isize,
}

impl PageIndex {
    #[pure]
    #[ensures(self.entry_count == isize::MIN ==> result == 0)]
    #[ensures(self.entry_count == 0 ==> result == 0)]
    #[ensures(result <= isize::MAX as usize)]
    pub const fn len(&self) -> usize {
        if self.entry_count < 0 {
            ((1_isize + self.entry_count) + isize::MAX) as usize
        } else {
            self.entry_count as usize
            
        }
    }

    #[pure]
    #[ensures(result == (self.len() == 0))]
    pub const fn is_empty(&self) -> bool {
        self.entry_count == isize::MIN || self.entry_count == 0
    }
}

const DEPTH: usize = 4;

#[trusted]
#[pure]
#[requires(index < DEPTH)]
#[ensures(result == page_indices[index])]
const fn get_page_index(page_indices: &[PageIndex; DEPTH], index: usize) -> PageIndex {
    // FIXME: is trusted due to error:
    // [Prusti internal error] generating fold-unfold Viper statements failed
    // this is already logged as a `verify_partial` test case in:
    // https://github.com/viperproject/prusti-dev/issues/709
    page_indices[index]
}

#[pure]
#[requires(index < DEPTH)]
#[ensures(result ==> entries[0] <= page_indices[0].len())]
#[ensures(forall(|i: usize| (result && index < DEPTH && 0 < i && i <= index) ==> (entries[i] < page_indices[i].len())) )]
const fn is_valid_path(
    page_indices: &[PageIndex; DEPTH],
    entries: &[usize; DEPTH],
    index: usize,
) -> bool {
    match index {
        index if index > 0 && index < DEPTH => {
            entries[index] < get_page_index(page_indices, index).len()
                && is_valid_path(page_indices, entries, index - 1)
        }
        index if index == 0 => entries[index] <= get_page_index(page_indices, index).len(),
        _ => false,
    }
}

pub struct Path {
    page_indices: [PageIndex; DEPTH],
    entries: [usize; DEPTH],
}

impl Path {
    #[pure]
    pub const fn invariant(&self) -> bool {
        self.page_indices.len() == DEPTH
            && self.entries.len() == DEPTH
            && is_valid_path(&self.page_indices, &self.entries, DEPTH - 1)
    }

    #[pure]
    #[requires(self.invariant())]
    #[requires(index < DEPTH)]
    #[ensures(result == self.page_indices[index])]
    pub const fn get_page_index(&self, index: usize) -> PageIndex {
        get_page_index(&self.page_indices, index)
    }
}

pub struct Cursor {
    path: Path,
}

impl Cursor {
    #[pure]
    #[requires(self.path.invariant())]
    #[requires(index < DEPTH)]
    #[ensures(result == self.path.get_page_index(index))]
    pub const fn get_page_index(&self, index: usize) -> PageIndex {
        self.path.get_page_index(index)
    }

    #[pure]
    pub const fn is_valid_page_index(&self, page_index: PageIndex) -> bool {
        !page_index.is_empty()
    }

    #[pure]
    #[requires(self.path.invariant())]
    #[ensures(forall(|i: usize| (result && index < DEPTH && 0 <= i && i <= index) ==> (self.is_valid_page_index(self.get_page_index(i)))) )]
    pub const fn is_valid_path(&self, index: usize) -> bool {
        match index {
            index if index > 0 && index < DEPTH => {
                self.is_valid_page_index(self.get_page_index(index)) && self.is_valid_path(index - 1)
            }
            index if index == 0 => self.is_valid_page_index(self.get_page_index(0)),
            _ => false,
        }
    }
}

fn main() {}
```

I haven't been able to figure out yet where the definition collector goes off the rails. I also considered whether the single `#[trusted]` in there might have something to do with it, but my thoughts are that it should not matter due to the `#[ensures(result == page_indices[index])]` post-condition on `const fn get_page_index(page_indices: &[PageIndex; DEPTH], index: usize) -> PageIndex` (the same goes for all the other `fn get_page_index`).

**Comment by Pointerbender** [comment]
More minimal reproduction:

```rust
use prusti_contracts::*;

pub struct PageIndex {
    entry_count: isize,
}

impl PageIndex {
    #[pure]
    #[ensures(self.entry_count == isize::MIN ==> result == 0)]
    #[ensures(self.entry_count == 0 ==> result == 0)]
    #[ensures(result <= isize::MAX as usize)]
    pub const fn len(&self) -> usize {
        if self.entry_count < 0 {
            ((1_isize + self.entry_count) + isize::MAX) as usize
        } else {
            self.entry_count as usize
            
        }
    }

    #[pure]
    #[ensures(result == (self.len() == 0))]
    pub const fn is_empty(&self) -> bool {
        self.entry_count == isize::MIN || self.entry_count == 0
    }

    #[pure]
    pub const fn foo(&self) -> bool {
        self.len() < 4
    }

    #[requires(self.foo())]
    pub const fn bar(&self) -> bool {
        !self.is_empty()
    }
}

fn main() {}
```

**Comment by Pointerbender** [comment]
W.r.t. the last minimal example, what I think is going on:

The errors are in the Viper program for:

```rust
    #[requires(self.foo())]
    pub const fn bar(&self) -> bool {
        !self.is_empty()
    }
```

The definition collector first walks the pre-condition of `bar` and in the process it determines it doesn't need a function body for `builtin$cast$isize$usize__$TY$__$int$$$int$`. With this small change the program actually compiles and verifies, despite the missing body for `builtin$cast$isize$usize__$TY$__$int$$$int$`:

```rust
    #[requires(self.foo())]
    pub const fn bar(&self) -> bool {
        true
    }
```

So far, it walked along `fn foo`, `fn len` and `builtin$cast$isize$usize__$TY$__$int$$$int$`. Next, it walks the method body for `bar` and comes across `fn is_empty()`, which directly depends on `fn len`, but does not directly depend on `builtin$cast$isize$usize__$TY$__$int$$$int$`. Since it already visited `fn len`, it does not get traversed again and the function body for `builtin$cast$isize$usize__$TY$__$int$$$int$` is not collected, my guess is somewhere in this code (although I'm not 100% yet):

https://github.com/viperproject/prusti-dev/blob/7e3cb69fe1348beeb652101ca6b80eb9548b8c0c/prusti-viper/src/encoder/definition_collector.rs#L369-L409

**Comment by Pointerbender** [comment]
I have a fix pending CI in PR #784. The trick was that the definition collector should revisit the pre- and post-conditions if it hadn't already done so during an earlier "direct" visitation :) It was a corner case where the pre- and post-conditions were already visited before, but not yet through a "direct call".

**Comment by vakaras** [comment]
A good catch! Thank you for investigating and fixing this!

**Comment by Pointerbender** [comment]
My pleasure! :-) Many thanks for all your feedback along the way!
