### ISSUE TITLE
Hello word fails to compile

### ISSUE THREAD

**Issue by ArbilGit** [viperproject/prusti-dev#790]
The hello world app fails to compile for me:

```
extern crate prusti_contracts;

fn main() {
    println!("Hello, world!");
}
```
with
```
1 | extern crate prusti_contracts;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

`Verify with Prusti` button in VSCode works (though rejects the app with `[Prusti: unsupported feature] unsupported constant type Ref('_#18r, [&str; 1], Not)`).

Environment: VSCode extension v0.9.0, LatestDev channel, rust nightly 1.59, Windows 10 x86 64. I have nothing prusti related in the `.toml`.

Thanks in advance!

**Comment by vakaras** [comment]
Hello, verification of programs that perform IO is currently not supported. (And very very complicated in general.)

**Comment by ArbilGit** [comment]
Sure! How to amend the failing import of `prusti_contracts`? That's my main problem

**Comment by vakaras** [comment]
What happens when you try to verify the following:

```rust
use prusti_contracts::*;

#[requires(x > 0)]
fn test(x: i32) {}

fn main() {
  test(-3);
}
```

**Comment by ArbilGit** [comment]
The precondition is checked correctly, and also errors due to unresolved import:
```
unresolved import `prusti_contracts`
use of undeclared crate or module `prusti_contracts`
cannot find attribute `requires` in this scope
[Prusti: verification error] precondition might not hold.
```

**Comment by vakaras** [comment]
Which edition are you using? Could you please try adding `edition = "2021"` to `Cargo.toml`?

**Comment by vakaras** [comment]
And also the following dependency:
```
prusti-contracts = { git = "https://github.com/viperproject/prusti-dev.git" }
```

**Comment by ArbilGit** [comment]
The edition was already 2021. The git dependency fixed it. Thank you so much!

A quick question please not to open a second issue: is prusti known not to work on Apple M1? On that machine it crashes on installation with wrong architecture of a `.dylib` library from Java folder

**Comment by vakaras** [comment]
> The edition was already 2021. The git dependency fixed it. Thank you so much!

In that case, the dependency error was most likely reported not by Prusti, but by Rust Analyzer.

> A quick question please not to open a second issue: is prusti known not to work on Apple M1? On that machine it crashes on installation with wrong architecture of a `.dylib` library from Java folder

Supporting Apple M1 is problematic because they are not supported yet by GitHub actions and I do not think anyone in our team has one. However, the contributions are welcome ☺.

**Comment by ArbilGit** [comment]
I see. Thank you once again. Now off to play with prusti!
