### ISSUE TITLE
Snapshot equality between empty tuples

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#81]
Two crates are failing the [top-20 test](https://github.com/viperproject/prusti-dev/actions/runs/146052591). The error message is
> thread 'main' panicked at 'not yet implemented: TyTuple([])', prusti-viper/src/encoder/snapshot_encoder.rs:129:18

I think it's because those crates use empty tuples.

@cmatheja Would it be easy to encode that empty tuples are always equal? The following program outputs `true`.
```rust
fn main() {
    println!("{}", () == ()); // true
}
```

**Comment by cmatheja** [comment]
Actually, I'm currently adding support for tuples anyway :-)
I didn't realize that tuples appear in the top-20 but not in the other tests until the CI complained.

**Comment by fpoli** [comment]
> I didn't realize that tuples appear in the top-20 but not in the other tests until the CI complained.

Ah, me neither. Good that we have so many tests :)

(We should rethink how to use issue labels, currently it's very fuzzy.)

**Comment by cmatheja** [comment]
Tuples are now supported - including empty ones. For example, the following verifies:

```rust
fn main() {
    let a = ();
    let b = ();
    assert!(a == b);
}

```
