### ISSUE TITLE
[Prusti internal error] `Consistency error: Local variable _5 not found` inside a pure function

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#815]
The following Rust program fails verification with error `[Prusti internal error] consistency error in A::test: Consistency error: Local variable _5 not found. (@0.0)`.

```rust
use prusti_contracts::*;

#[derive(Clone, Copy)]
pub struct A {
    inner: isize,
}

impl A {
    #[pure]
    #[requires(num < isize::MAX as usize)]
    pub fn new(num: usize) -> Self {
        Self {
            inner: num as isize + isize::MIN,
        }
    }

    #[pure]
    pub fn test(&self) {
        let _ = Self::new(2);
    }
}

fn main() {}
```

This error is found in the resulting Viper program for `A::test` in the pure function for `A::new`:

```
function m_new__$TY$__(_1: Int): Snap$struct$m_A
  requires true
  requires _1 < builtin$cast$isize$usize__$TY$__(9223372036854775807)
  requires 0 <= _1
  requires _1 <= 18446744073709551615
  ensures true
  ensures [result == mirror_simple$m_new__$TY$__(_1), true]
{
  (
    !(
      builtin$cast$usize$isize__$TY$__(_1) + -9223372036854775808 < -9223372036854775808
      || builtin$cast$usize$isize__$TY$__(_1) + -9223372036854775808 > 9223372036854775807
    ) ? cons$0$__$TY$__Snap$struct$m_A$(_5.tuple_0.val_int) : builtin$unreach__$TY$__Snap$struct$m_A$()
  )
}
```

where it tries to access `_5.tuple_0.val_int` (the result of the checked addition `num as isize + isize::MIN`), but `_5` is not in the scope of the function. In fact, `_5` is not declared anywhere in the Viper program for `A::test` (it seems to have spilled over from the Viper program for `A::new` somehow, where it is declared inside `method m_new()`).

**Comment by fpoli** [comment]
Thanks for the report! This seems a bug in the replacements done to encode pure code. Probably

https://github.com/viperproject/prusti-dev/blob/e9edf18d1c6fa99cb4eaac1180d67e3837a661c1/prusti-viper/src/encoder/mir/pure/interpreter/mod.rs#L224-L226

or 

https://github.com/viperproject/prusti-dev/blob/e9edf18d1c6fa99cb4eaac1180d67e3837a661c1/prusti-viper/src/encoder/mir/pure/pure_functions/interpreter.rs#L992-L994

(There is a refactoring in progress, thus the code duplication.)

**Comment by Pointerbender** [comment]
Another example where this error pops up (on the latest version of the `master` branch as-of the merge of #831, before this PR it used to give a different error):

```rust
#[pure]
#[requires(0 <= i && i < 10)]
const fn get(a: &[i32; 10], i: usize) -> i32 {
    a[i]
}

#[requires(0 <= i && i < 10)]
#[ensures(forall(|j: usize| (0 <= j && j < 10 && j != old(i)) ==> (get(a, j) == old(get(a, j))), triggers=[(get(a, j),)]))]
#[ensures(get(a, i) == old(v))]
fn set(a: &mut [i32; 10], i: usize, v: i32)  {
    a[i] = v;
}
```

Results in these errors for `fn set`:

```
error: [Prusti internal error] consistency error in selection_sort::set: Consistency error: No matching identifier closure_0 found of type Field. (@17.113)

error: [Prusti internal error] consistency error in selection_sort::set: Consistency error: No matching identifier tuple_0 found of type Field. (@0.0)

error: [Prusti internal error] consistency error in selection_sort::set: Consistency error: Local variable _8 not found. (@0.0)
```

The offending Viper code is the last assert statement for the functional specification of the post-condition:

```
  assert (let _LET_0 == (old[pre](_2)) in (
    forall _0_quant_0: Int ::
    { m_get__$TY$__(snap$__$TY$__Snap$Array$10$i32$(_8.tuple_0.tuple_0.closure_0.val_ref.val_ref), _0_quant_0) }
    0 <= _0_quant_0 && _0_quant_0 <= 18446744073709551615 ==>
      !(0 <= _0_quant_0) || (!(_0_quant_0 < 10) || (
        _0_quant_0 == _LET_0 ||
        m_get__$TY$__(snap$__$TY$__Snap$Array$10$i32$(_old$pre$0), _0_quant_0)
        == old[pre](m_get__$TY$__(snap$__$TY$__Snap$Array$10$i32$(_1.val_ref), _0_quant_0))
      ))))
      && m_get__$TY$__(snap$__$TY$__Snap$Array$10$i32$(_old$pre$0), old[pre](_2))
      == old[pre]((unfolding acc(i32(_3), write) in _3.val_int))
```

If the `_8.tuple_0.tuple_0.closure_0.val_ref.val_ref` within the trigger is replaced with any valid expression (e.g. `_1.val_ref`, `_old$pre$0`) then the whole Viper program verifies okay.

I will try to dig a little deeper on how to resolve this error during this weekend :)

**Comment by Aurel300** [comment]
That `_8.tuple_0.tuple_0.closure_0.val_ref.val_ref` bit looks like a trigger didn't get encoded properly. The code responsible is:

https://github.com/viperproject/prusti-dev/blob/19371627b7bad75a6e839d6dabe2c0bd9e5bc680/prusti-viper/src/encoder/mir/pure/specifications/encoder_poly.rs#L162-L179

In particular, the third argument to `inline_closure` should indicate what each argument of the encoded trigger expression (which itself is encoded as a closure with the same arguments as the quantifier's bound vars) should correspond to.

This is a place to start looking; I will have time to look at this again on Tuesday in any case :)

**Comment by Pointerbender** [comment]
> In particular, the third argument to `inline_closure` should indicate what each argument of the encoded trigger expression (which itself is encoded as a closure with the same arguments as the quantifier's bound vars) should correspond to.
> 
> This is a place to start looking; I will have time to look at this again on Tuesday in any case :)

I'm finding this one particularly tricky to debug :) As far as I can tell, the code in `encoder_poly.rs` is doing the right thing. It almost seems like it is not registering the substitutions for the function arguments to `fn set` that are used in the triggers, e.g.

```rust
#[ensures(forall(|j: usize| (0 <= j && j < 10 && j != old(i)) ==> (get(a, j) == old(get(a, j))), triggers=[(get(a, j),)]))]
fn set(a: &mut [i32; 10], i: usize, v: i32)  {}
```

Here `a` becomes `_1.val_ref`/`_old$pre$0` inside the Viper method body and inside the quantifier body, but `a` in the trigger is never substituted for something else (leaving `_8.tuple_0.tuple_0.closure_0.val_ref.val_ref` in its place). There is some substitution happening somewhere, because the other calls to `get` in the quantifier body also start out wrapped in a closure and these are properly replaced with its proper encoding (plus the call to `get` and the snap app to its argument are also properly materialized in the quantifier trigger). I deducted that this "setting up of substitutions" does not seem to be happening in `encoder_poly.rs`, though. So far I was not able to find where Prusti sets up the substitutions for the quantifier body and triggers. I'm still combing through the PR in the hopes of spotting it, but so far without success :) If I can find it, I'm hoping that either it turns out that the code is either forgetting to set the substitution for the function arguments or otherwise spot why it doesn't match with what comes out of `encoder_poly.rs`.

**Comment by Pointerbender** [comment]
I have one more hunch for this one: it might be that the triggers are not properly folded during the folding or ForAll expressions (and thus failing to substitute the correct variables). Two potential candidates I identified so far are:

https://github.com/viperproject/prusti-dev/blob/68d1b15bd8263c1e5672e6dae95588d5c3d14884/vir/defs/polymorphic/ast/expr_transformers.rs#L239-L252

and

https://github.com/viperproject/prusti-dev/blob/68d1b15bd8263c1e5672e6dae95588d5c3d14884/vir/defs/polymorphic/ast/expr_transformers.rs#L843-L856

I'll try to debug some more tonight :)

**Comment by Pointerbender** [comment]
> I have one more hunch for this one: it might be that the triggers are not properly folded during the folding or ForAll expressions (and thus failing to substitute the correct variables). Two potential candidates I identified so far are:

This hunch turned out to be a dead end :) Prusti seems to be registering the trigger closure for `get(a, j)` okay under Viper variable `_10`. From what I can gather, the encoding goes something like this:

* `_8` is of type `((trigger_closure,),)`
* `_9` is of type `(trigger_closure,)`
* `_10` is of type `trigger_closure` (correctly found by `SpecsClosuresCollector` in `prusti-viper/src/encoder/specs_closures_collector.rs`)
* `_11` is of type `(body_closure,)`
* `_12` is of type `body_closure`

Then in the trace logs I think I see Prusti trying to replace `_10` with `_1` at some point (if it was able to do this, then I believe `_8.tuple_0.tuple_0.closure_0.val_ref.val_ref`/`_10.closure_0.val_ref.val_ref` would be correctly translated to `_1.val_ref` in the Viper program). However, the `body_replacement` offered by `fn encode_quantifier` (from `encoder_poly.rs`) suggests to replace:

```
        Field(
            FieldExpr {
                base: Local(
                    Local {
                        variable: _1: Ref(ref$closure$m_prusti_post_item_set_0bdd4d65df10483c8b15cad1f39d94db$$$opencur$closure$sharp$0$closecur$),
                        position: Position {
                            line: 0,
                            column: 0,
                            id: 0,
                        },
                    },
                ),
                field: val_ref: Ref(closure$m_prusti_post_item_set_0bdd4d65df10483c8b15cad1f39d94db$$$opencur$closure$sharp$0$closecur$),
                position: Position {
                    line: 0,
                    column: 0,
                    id: 0,
                },
            },
        ),
```

with

```
        Field(
            FieldExpr {
                base: Field(
                    FieldExpr {
                        base: Local(
                            Local {
                                variable: _8: Ref(tuple1$tuple1$closure$m_prusti_post_item_set_0bdd4d65df10483c8b15cad1f39d94db$$$opencur$closure$sharp$0$closecur$),
                                position: Position {
                                    line: 0,
                                    column: 0,
                                    id: 0,
                                },
                            },
                        ),
                        field: tuple_0: Ref(tuple1$closure$m_prusti_post_item_set_0bdd4d65df10483c8b15cad1f39d94db$$$opencur$closure$sharp$0$closecur$),
                        position: Position {
                            line: 0,
                            column: 0,
                            id: 0,
                        },
                    },
                ),
                field: tuple_0: Ref(closure$m_prusti_post_item_set_0bdd4d65df10483c8b15cad1f39d94db$$$opencur$closure$sharp$0$closecur$),
                position: Position {
                    line: 0,
                    column: 0,
                    id: 0,
                },
            },
        ),
    ),
```

In this case `encoded_args[0]` is variable `_8` of type `((trigger_closure,),)`. Then substitution fails because Prusti attempts to replace `_10` with `_1` afterwards and it doesn't realize `_8.tuple_0.tuple_0` is the same as `_10` in this case.

Perhaps it's tripping up on the nested tuple during the encoding step, somewhere around here:

https://github.com/viperproject/prusti-dev/blob/2a71e807e637751d62728a2627c71913acfeed85/prusti-viper/src/encoder/encoder.rs#L404-L421

At first glance, in the case of nested tuples it seems to return the `base` of the inner tuple instead of the most inner value contained in the nested tuple. Although I didn't fully search through this avenue yet, and at this point I'm not so sure what I'm looking for anymore :sweat_smile: Most likely I'm missing some key insight that would clear this up. Maybe you'll have more luck than me tomorrow @Aurel300, hopefully some of my debugging is helpful in the process :)
