### ISSUE TITLE
Logging to file on Windows fails

### ISSUE THREAD

**Issue by JonasAlaif** [viperproject/prusti-dev#827]
The `log_dir` default value (`"./log/"`) will cause a panic on Windows; there is should instead be `r".\log\"`. Maybe we could just use `"log"` in this case instead? Or save the `log_dir` value as a `PathBuf`? This is likely a more widespread issue, wherever a `"some/path/here": &str` is used instead of a `["some", "path", "here"].iter().collect(): PathBuf`.
Additionally, the filename chosen for the logged viper file (`program.name + ".vpr"`) causes a crash in cases where illegal characters are included (e.g. `:`). This happens for instance when translating trait functions: `.\log\viper_program\test_file.rs_Trait::fn.vpr`.
A fix of this issue should also add config tests to the CI where Prusti is run with various configurations to check for crashes.

**Comment by vakaras** [comment]
> Or save the `log_dir` value as a `PathBuf`? This is likely a more widespread issue, wherever a `"some/path/here": &str` is used instead of a `["some", "path", "here"].iter().collect(): PathBuf`.

I would say that this is a preferred solution.

**Comment by fpoli** [comment]
Yep, `log_dir` should return a `PathBuf`.

**Comment by fpoli** [comment]
Where does the panic come from? `PathBuf` should happily accept `"./log/"`.

**Comment by JonasAlaif** [comment]
Sounds good. The problematic lines are [here](https://github.com/viperproject/prusti-dev/blob/af6ce8cf000e3f3b8e63ceb2fbd925be1909583d/prusti-common/src/report/log.rs#L15-L16).
And for the filename, [here](https://github.com/viperproject/prusti-dev/blob/af6ce8cf000e3f3b8e63ceb2fbd925be1909583d/prusti-common/src/report/log.rs#L37-L38) (specifically that `name_path` might not be a valid filename).
The error results in a panic [here](https://github.com/viperproject/prusti-dev/blob/af6ce8cf000e3f3b8e63ceb2fbd925be1909583d/prusti-common/src/report/log.rs#L51).

**Comment by fpoli** [comment]
> Sounds good. The problematic lines are [here](https://github.com/viperproject/prusti-dev/blob/af6ce8cf000e3f3b8e63ceb2fbd925be1909583d/prusti-common/src/report/log.rs#L15-L16).

I see, good catch! I'm not sure why it doesn't fail on CI.
