### ISSUE TITLE
Returning immutable reference causes fold-unfold error

### ISSUE THREAD

**Issue by vl0w** [viperproject/prusti-dev#838]
Returning an immutable borrow of a struct field causes a fold-unfold error:
```rust
struct Foo {
    x: i32
}

fn get_x(foo: &Foo) -> &i32 {
    &foo.x
}

#[requires(foo.x > 42)]
fn verify(foo: Foo) {
    let x: &i32 = get_x(&foo);
    assert!(*x > 42);
}

fn main() {}
```

The error:
```
cannot generate fold-unfold Viper statements. The required permission Pred(_old$l3$0, read) cannot be obtained.
```

When removing the type annotation of `x` in `verify`, the error disappears but the program does not verify (`assert!(*x > 42)` does not verify).

**Comment by Aurel300** [comment]
I think for the assertion to verify you still need a spec on `get_x`. But of course the crash with type annotation issue remains.

**Comment by vl0w** [comment]
> I think for the assertion to verify you still need a spec on `get_x`. But of course the crash with type annotation issue remains.

Indeed :-)

Here's even a simpler example without any structs involved:
```rust
fn foo(x: &i32) -> &i32 {
    x
}

fn verify() {
    let x = 5;
    let y: &i32 = foo(&x);
}
```

**Comment by fpoli** [comment]
I currently would expect an "unsupported feature" error message from Prusti. The encoding of returning shared references that reborrow one of the parameters is not yet defined.

From the log of the latest example I see that the postcondition of `foo` happens to generate a `acc(..., read()) --* acc(..., read())` magic wand, whose application crashes the fold-unfold generation. However, the magic wand is not necessary in the first place because the returned reference doesn't block access to any of the parameters.

**Comment by fpoli** [comment]
~~Always in the latest example, even if `foo` contains the (unnecessary) magic wand in its postcondition, and even if the expiration of the borrows at the end of `verify` expects to be able to apply that magic wand, the encoding of the `foo(&x)` call doesn't actually provide (inhale) it.~~

**Comment by fpoli** [comment]
Related: https://github.com/viperproject/prusti-dev/issues/452

**Comment by fpoli** [comment]
> When removing the type annotation of `x` in `verify`, the error disappears

I consider that a lucky coincidence. Even if no errors are reported, the encoding might be wrong.

**Comment by JonasAlaif** [comment]
> > When removing the type annotation of `x` in `verify`, the error disappears
> 
> I consider that a lucky coincidence. Even if no errors are reported, the encoding might be wrong.

The type annotation does make a difference in Rust:
```rust
let y: &i32 = foo(&x);
```
is the same as writing:
```rust
let y = &*foo(&x);
```
Note the `&*` reborrow (vs `let y = foo(&x);`), which creates a new reference with a new (possibly shorter) lifetime. The difference in resulting Rust MIR is probably what somehow results in the fold-unfold error. When I last checked Prusti wasn't so good at handling multiple simultaneous immutable borrows and so this well could be what is causing the fold-unfold issue.
