### ISSUE TITLE
"Inhale might fail" when passing reference to a predicate and accessing field in the same specification

### ISSUE THREAD

**Issue by emlaufer** [viperproject/prusti-dev#852]
An error occurs when using a specification that accesses both a reference's field and passes the reference to a predicate:
```
pub struct Bar {
    val: bool,
}

#[requires(bar.val && pred(bar))]
fn foo(bar: &Bar) {}

predicate! {
    pub fn pred(bar: &Bar) -> bool {
        true
    }
}
```
The full error output:
```
[Prusti internal error] unregistered verification error: [inhale.failed:insufficient.permission; 0] Inhale might fail. There might be insufficient permission to access _1.val_ref.f$val (@0.0)
```

The program verifies if the specification is changed into two separate `requires` statements instead.

**Comment by vakaras** [comment]
Thank you for reporting this! It should be eventually get fixed by my refactorings.
