### ISSUE TITLE
Failing crates in the top-500 test

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#87]
There are a few crates on which `cargo-prusti` fails, as reported in the [top-500 test](https://pmbuilds.inf.ethz.ch/job/Prusti/job/prusti-top-500-crates/201/).

### Panic
> 'not yet implemented: TyParam(T/#0)', prusti-viper/src/encoder/type_encoder.rs:128:22
- [x] `074_futures`
- [x] `111_num-complex`
- [x] `342_euclid`
- [x] `348_cgmath`

### Consistency error
> No matching identifier equals$__$TY$__m_log$$Level$opensqu$0$closesqu$$_beg_$_end_$m_log$$LevelFilter$opensqu$0$closesqu$$_beg_$_end_$$bool$ found of type Function
- [x] `002_log`
- [ ] `423_h2`

### Unregistered verification error
> [function.not.wellformed:insufficient.permission] Function might not be well-formed. There might be insufficient permission to access _arg.f$0.
- [x] `341_winit`

### Timeout
- [ ] `033_unicode-normalization` (see issue #77)

**Comment by cmatheja** [comment]
After the update, verification fails for three crates:

- ```033_unicode-normalization``` (timeout)
- ```199_tokio-threadpool``` (fold-unfold issue)
- ```423_h2``` (consistency error in code generated by the snapshot encoder)

**Comment by fpoli** [comment]
Superseded by #169
