### ISSUE TITLE
optimize_folding doesn't correctly handle disjunctions

### ISSUE THREAD

**Issue by JonasAlaif** [viperproject/prusti-dev#874]
The following example fails, due to an incorrect Viper encoding:
```rust
use prusti_contracts::*;
fn main() { }

#[requires(match x {
    Some(v) => *v > 0,
    None => true,
})]
fn foo(x: &mut Option<i32>) {}
```
Specifically we generate:
```boogie
inhale unfolding acc(m_Option$_beg_$i32$_end_Some(_1.val_ref.enum_Some), read$()) in
    unfolding acc(i32(_1.val_ref.enum_Some.f$0), read$()) in
        _1.val_ref.discriminant == 0 || _1.val_ref.enum_Some.f$0.val_int > 0
```
But we should instead be generating:
```boogie
inhale _1.val_ref.discriminant == 0 || (
    unfolding acc(m_Option$_beg_$i32$_end_Some(_1.val_ref.enum_Some), read$()) in
        unfolding acc(i32(_1.val_ref.enum_Some.f$0), read$()) in
            _1.val_ref.enum_Some.f$0.val_int > 0
)
```
(We try to unfold `acc(m_Option$_beg_$i32$_end_Some(_1.val_ref.enum_Some), read$())` even though the enum might be None: `_1.val_ref.discriminant == 0`)

Using `git bisect` I get that the error was introduced by merging in #831 (3a64463127390f52810245cda6f30e34a7b621a6). @Aurel300 any ideas?

May be related to issue #701 though the error is different here and seems easier to fix.

**Comment by fpoli** [comment]
~~My guess: https://github.com/viperproject/prusti-dev/pull/831#discussion_r792055611~~

Actually, that's for `procedure_encoder.rs`, so I don't see how it could affect the encoding of the pure expression.

**Comment by fpoli** [comment]
The fold-unfold algorithm generates the correct expression. Something that runs later (an optimization pass?) breaks it.

**Comment by fpoli** [comment]
Inseed, disabling `optimize_folding` the error disappears. 

```
-Poptimizations=inline_constant_functions,delete_unused_predicates,remove_empty_if,purify_vars,fix_quantifiers,remove_unused_vars,remove_trivial_assertions,clean_cfg
```

**Comment by JonasAlaif** [comment]
Yeah, it seems to me that the optimisation incorrectly pushes in the `_1.val_ref.discriminant == 0 || `. No idea where I would find the issue in the code however - ~~I can run a `git bisect` on the erroring PR~~ (Aurel force pushed things aha)

**Comment by Aurel300** [comment]
@JonasAlaif Yeah, sorry, I was going to split the PR into individual commits, but anyway the intermediate commits would not compile. I did not want to spend the time figuring out how to re-do the changes atomically with working intermediate steps too…
