### ISSUE TITLE
Wrong encoding of snapshots in postcondition

### ISSUE THREAD

**Issue by JonasAlaif** [viperproject/prusti-dev#884]
The following snippet causes a fold-unfold error in `main`. However, this is misleading and not due to the fold-unfold algorithm.
```rust
use prusti_contracts::*;

#[pure]
fn foo<T>(y: &T) -> bool { true }
#[ensures(foo(&x))]
fn bar<T>(x: T) {}

struct S(i32);
fn main() {
    let s = S(0);
    bar(s);
}
```
The real culprit is that the `foo(&x)` postcondition is encoded as `foo(snap(x))` rather than the correct `foo(old(snap(x)))`.
This means that at the call of `bar(s)` we generate:
```vim
label l1
exhale acc(struct_S(s), write)
inhale foo(snap(s))
```
rather than the correct:
```vim
inhale foo(old[l1](snap(s)))
```

**Comment by JonasAlaif** [comment]
There may be other related issues to this, but I found them impossible to find due to the super ambiguous error of `cannot generate fold-unfold Viper statements`

**Comment by fpoli** [comment]
> this is misleading and not due to the fold-unfold algorithm

In general, a fold-unfold error means that the encoding has permission errors that cannot be fixed just by folding or unfolding predicates. For example, trying to exhale a predicate twice.

The current error message is
```
cannot generate fold-unfold Viper statements. The required permission Pred(_3, read) cannot be obtained.
```

Would it be better to expand it to the following?
```
Details: cannot generate fold-unfold Viper statements. The required permission Pred(_3, read) cannot be obtained by folding or unfolding other predicates.
```

**Comment by fpoli** [comment]
In case of fold-unfold error, it might also be useful to to generate a special dump, mentioning in the error message the specific CFG block and statement where the error occurred.

**Comment by JonasAlaif** [comment]
That might slightly improve the understandability of the error message (re: https://github.com/viperproject/prusti-dev/issues/884#issuecomment-1048818555), but my issue with it is more fundamental - this kind of thing should never reach the fold-unfold algorithm in the first place. That isn't really realistic though and so probably the best we can do is to much improve the error reporting of fold-unfold errors I.e. it's completely unclear to me when I see `The required permission Pred(_3, read) cannot be obtained` as to what caused the issue - what does `_3` correspond to (e.g. we could at least print the type) and which part of the code triggered this issue (e.g. right now the position information highlights the failing function, but actually the error is due to the encoding of `ensures(foo(&x))` - we know that the `Pred(_3, read)` we are trying to get is actually from there, and not from `main`, so we could try to improve the error position when reporting these errors)

**Comment by fpoli** [comment]
I completely agree with your message. The "never reach the fold-unfold algorithm in the first place" should be ensured by the "unsupported feature" errors, but in practice many of them are missing (e.g. #838). Adding the location and type to the error messages would help a lot, yes. It should be enough to propagate the location down to the place where the error is constructed; I'll give a look. In the end, however, a fold-unfold error (usually) means that there is an error at the Viper level, so debugging would always require to look at the encoding.

**Comment by fpoli** [comment]
Actually, to report the fold-unfold error messages on the source code what is currently missing is a mapping from VIR statements back to MIR. We could modify the pure and impure encoders to also generate a map from `vir::Position` to `mir::Location` (or `FxHashSet<Location>`...). So far the `vir::Position` has only been used to generate error messages, so we probably don't generate positions for VIR statements and expressions that are not meant to fail, but it looks like the best way to proceed. As a bonus, we would even be able to map back to the source code unexpected Viper error messages.
