### ISSUE TITLE
Nested `unfolding (...) in ...` statements trying to unfold the same predicate

### ISSUE THREAD

**Issue by Pointerbender** [viperproject/prusti-dev#892]
The following Rust program:

```rust
fn main() {}

#[derive(Clone, Copy)]
pub enum Foo {
    Bar,
}

#[trusted]
#[ensures(match result {
    Ok(Some(r)) => r < 100,
    _ => true,
})]
pub fn foo() -> Result<Option<usize>, Foo> {
    unimplemented!()
}

pub fn test() -> Result<usize, Foo> {
    match foo() {
        Err(error) => Err(error),
        Ok(opt) => match opt {
            Some(res) => Ok(res),
            None => Err(Foo::Bar),
        },
    }
}
```

Generates the following error when the `optimize_folding` optimization is disabled:

> error: [Prusti internal error] Prusti encountered an unexpected internal error
>  |
>  = help: This could be caused by too small assertion timeout. Try increasing it by setting the configuration parameter ASSERT_TIMEOUT to a larger value.
>  = note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new
>  = note: Details: unregistered verification error: [inhale.failed:insufficient.permission; 0] Inhale might fail. There might be insufficient permission to access `m_Result$_beg_$m_Option$_beg_$usize$_end_$_sep_$struct$m_Foo$_end_Ok(_1.enum_Ok)` (@0.0)

The error goes away and the program verifies okay when enabling the `optimize_folding` optimization. However, this optimization is causing some of my other programs to fail, so I'd like to keep `optimize_folding` disabled. Note that `optimize_folding` will go away when the refactoring lands.

The relevant Viper code looks like this:

```
inhale /* ... */
      unfolding acc(m_Result$_beg_$m_Option$_beg_$usize$_end_$_sep_$struct$m_Foo$_end_Ok(_1.enum_Ok), write) in (
        unfolding acc(m_Option$_beg_$usize$_end_(_1.enum_Ok.f$0), write) in (
          // unfolding acc(m_Result$_beg_$m_Option$_beg_$usize$_end_$_sep_$struct$m_Foo$_end_Ok(_1.enum_Ok), write) in (
            // unfolding acc(m_Option$_beg_$usize$_end_(_1.enum_Ok.f$0), write) in (
              unfolding acc(m_Option$_beg_$usize$_end_Some(_1.enum_Ok.f$0.enum_Some), write) in (
                unfolding acc(usize(_1.enum_Ok.f$0.enum_Some.f$0), write) in _1.enum_Ok.f$0.enum_Some.f$0.val_int
              )
            // )
          // )
        ) < 100
      )
      /* ... */
```

With the 2 `unfolding` expressions commented out it verifies, but when those are present the verification fails (= with `optimize_folding` disabled).

I have a local patch that can solve this when `optimize_folding` is disabled. I'm just creating this issue to create the regression test and PR against :) I'm currently still running some tests, the PR will follow when all tests are passing.

**Comment by fpoli** [comment]
Thanks for pointing to the redundant unfoldings! A smaller program to reproduce the issue:
```rust
use prusti_contracts::*;

#[trusted]
#[ensures(match result {
    Ok(Some(r)) => r < 100,
    _ => true,
})]
pub fn foo() -> Result<Option<usize>, ()> {
    unimplemented!()
}

pub fn main() {
    let _ = foo();
}
```

**Comment by fpoli** [comment]
In VIR (`log/vir_program_before_viper/...`), one of the duplicated unfoldings has an additional `<variant {Some}>` in the inner expression:
```
unfolding acc(Ref(m_Option$_beg_$usize$_end_)(_1[enum_Ok].f$0), write) in (
    ...
    unfolding acc(Ref(m_Option$_beg_$usize$_end_)<variant {Some}>(_1[enum_Ok].f$0), write) in (...)
)
```

I suspect there is some equality definition that is too strict and doesn't recognize that the two translate to the same Viper predicate.

**Comment by Pointerbender** [comment]
Thanks for the additional example! I added this as a second regression test in PR #893.

> I suspect there is some equality definition that is too strict and doesn't recognize that the two translate to the same Viper predicate.

The only other equality check that I spotted is here:

https://github.com/viperproject/prusti-dev/blob/6c0f3dedd8ce141f9df4792750f3d90d8da8b7b4/vir/defs/polymorphic/ast/expr.rs#L2457-L2472

But this also compares `base` which should not be the case when checking predicate equality for the `unfolding`s.

**Comment by Pointerbender** [comment]
> I suspect there is some equality definition that is too strict and doesn't recognize that the two translate to the same Viper predicate.

I had another look, but I can't find any other places in the code that compares predicates other than `prusti-common/src/vir/optimizations/folding/expressions.rs` (this code uses the correct equality checks), but the code in this file is not executed when the `optimize_folding` optimization is disabled. It looks like it was meant to solve the same problem with the nested redundant unfoldings, but unfortunately enabling this optimization causes other programs to fail on my end :)

**Comment by fpoli** [comment]
I'd keep this open, because generating those nested unfoldings is a bug.
