### ISSUE TITLE
Caching prevents resolution of consistency errors

### ISSUE THREAD

**Issue by JonasAlaif** [viperproject/prusti-dev#894]
The following test case, which would cause a `consistency error` was recently fixed
```bash
echo "use prusti_contracts::*;
use std::cmp::{Ord, Ordering};
#[extern_spec]
trait Ord {
    #[pure]
    fn cmp(&self, other: &Self) -> Ordering;
}
#[pure]
fn compare<T: Ord>(a: &T, other: &T) -> Ordering {
    a.cmp(other)
}
fn main() {}" >> test_file.rs
```
If one creates a cache file (running into the `consistency error`) before the fix
```bash
git checkout 6c0f3dedd8ce141f9df4792750f3d90d8da8b7b4
./x.py build --all
PRUSTI_CACHE_PATH=./cache.bin ./target/debug/prusti-rustc --edition=2018 ./test_file.rs
```
And then uses that cache file with a version of Prusti where the `consistency error` shouldn't happen, caching will still erroneously report an error:
```bash
git checkout dde61004e91da0ceafe1addb26fddf3894b513ea
./x.py build --all
PRUSTI_CACHE_PATH=./cache.bin ./target/debug/prusti-rustc --edition=2018 ./test_file.rs
./target/debug/prusti-rustc --edition=2018 ./test_file.rs
```
(The command with caching fails, but the one without caching does not)

**Comment by JonasAlaif** [comment]
So this isn't an issue specific to consistency errors, it just seems that the types of function signatures aren't included in the hash for some reason: [hash implement here](https://github.com/viperproject/prusti-dev/blame/master/vir/src/legacy/ast/common.rs#L292-L296). @vakaras any idea why that is, could I just `#[derive(Hash)]` instead?

**Comment by vakaras** [comment]
The hash should ignore positions. Everything else is a bug.

**Comment by fpoli** [comment]
@JonasAlaif I think the hash used for caching *must* include the position, because the verification result references AST nodes by the id of their position.

@vakaras What is the use case for the hash that ignore positions?

**Comment by vakaras** [comment]
> @vakaras What is the use case for the hash that ignore positions?

Not sure. You implemented it… ☺

**Comment by fpoli** [comment]
I see, I didn't realize it's still used in VIR 2.0. Then, we have two different use cases for equality+hashing: caching needs the strong definition that considers positions, the encoding the weak one that ignores positions.

**Comment by vakaras** [comment]
> I see, I didn't realize it's still used in VIR 2.0. Then, we have two different use cases for equality+hashing: caching needs the strong definition that considers positions, the encoding the weak one that ignores positions.

For VIR 2.0 we could easily derive `PositionedHash`.

**Comment by JonasAlaif** [comment]
Hmm so far caching has been ignoring Position and it's been working fine, I guess very rarely is it the case that the position changes without the hash changing (e.g. due to adding an earlier line which caused the position change)

**Comment by fpoli** [comment]
It's easy to trigger. You need to first verify this program in the IDE
```rust
use prusti_contracts::*;

fn a() {}

#[ensures(false)]
fn test() {}

fn main() {}
```
Then, you comment `fn a() {}` and the next Prusti run will fail with an internal error, because the verification request to verify `test` is the same as before, but with different positions. So, the cached verification result will have the wrong position.
```rust
use prusti_contracts::*;

//fn a() {}

#[ensures(false)]
fn test() {}

fn main() {}
```
I think we should have an open issue for this.
