### ISSUE TITLE
Prusti internal error on &Vec -> slice coercion

### ISSUE THREAD

**Issue by enjhnsn2** [viperproject/prusti-dev#942]
It is a common pattern in Rust to implement array operations on slices and reuse this implementation on other containers of contiguous values by coercing these containers into slices  (e.g., implement `sum` for `&[u8]` and reuse this for  `Vec<u8>`). 
This pattern currently raises an internal error in Prusti.

For example, invoking a function with a `&Vec<u8>` works correctly:
```
pub fn vec_len(v: &Vec<u8>) -> usize {
    v.len()
}

pub fn test_vec_len() -> usize {
    let v = Vec::new(); 
    vec_len(&v)
}
```

as does invoking a function with a `&[u8]`
```
pub fn slice_len(s: &[u8]) -> usize {
    s.len()
}

pub fn test_slice_len() -> usize {
    let s: [u8; 4] = [0,1,2,3]; 
    slice_len(&s)
}
```

however, attempting to use the slice coercion pattern yields an error:

```
// fails
pub fn test_coerce() -> usize {
    let v = Vec::new(); 
    slice_len(v.as_slice())
}
```
with the error:
```
error: [Prusti internal error] cannot generate fold-unfold Viper statements. The required permission Pred(_old$l4$0, read) cannot be obtained.
```

If I recall correctly, slice coercion is implemented using the `Deref` trait, which may be the cause of the error, but thats just a guess.

Thanks for the help.

**Comment by JonasAlaif** [comment]
Hmm I can't seem to reproduce the issue. I've tried:
```rust
pub fn slice_len(s: &[u8]) -> usize {
    s.len()
}

pub fn test_coerce() -> usize {
    let v = Vec::new();
    slice_len(&v);
    slice_len(v.as_slice())
}
```
But I get `Successful verification` as expected.
Are you sure that you're running the LatestDev version of Prusti, or have the latest master code?

**Comment by enjhnsn2** [comment]
Ah, I was using a version of Prusti that was a few weeks old. It seems to not crash on the most recent version of Prusti. Sorry about that!
