### ISSUE TITLE
Unsoundness when using len() function of arrays and slices

### ISSUE THREAD

**Issue by cmatheja** [viperproject/prusti-dev#999]
Prusti appears to be unsound when one uses the `len()` function of arrays and slices within loops or at least in loop invariants.
For example, the following implementation of a binary search verifies:

```rust
#![allow(dead_code)]
use prusti_contracts::*;

fn search(a: &[i32], key: i32) -> Option<usize> {
  if a.len() == 0 {
    return None 
  }
  let mut low = 0;
  let mut high = a.len() - 1;
  while {
    body_invariant!(high < a.len());
    low <= high
  } {
    let mid = (low+high) / 2; // UNSOUND: this could overflow if initially high >> usize::MAX / 2
    let mid_val = a[mid];
    if mid_val < key {
      low = mid + 1;
    } else if mid_val > key {
        if mid == 0 {
            return None
        } else {
            high = mid - 1
        }
    } else {
      return Some(mid);
    }
  }
  None
}
```

However, if we replace `a.len()` within the loop by a variable `len` which is initially assigned to `a.len()`, then Prusti reports that verification fails due to a possible overflow:

```rust
#![allow(dead_code)]
use prusti_contracts::*;

fn search2(a: &[i32], key: i32) -> Option<usize> {
  let len = a.len(); // use len instead of a.len() from now on
  if len == 0 {
    return None 
  }
  let mut low = 0;
  let mut high = len - 1;
  assert!(high < len);
  
  while {
    body_invariant!(high < len);
    low <= high
  } {
    let mid = (low+high) / 2; // assertion might fail with "attempt to add with overflow"
    let mid_val = a[mid];
    if mid_val < key {
      low = mid + 1;
    } else if mid_val > key {
        if mid == 0 {
            return None
        } else {
            high = mid - 1
        }
    } else {
      return Some(mid);
    }
  }
  None
}
```

**Comment by Pointerbender** [comment]
@cmatheja this is because of #733 : the return value of `<[T]>.len()` is always guaranteed to be at most `isize::MAX` (for non-zero sized `T`) by the Rust type system, because references to allocations larger than `isize::MAX` bytes are forbidden by Rust. This series of statements then ensues:

```rust
high < a.len()
high < isize::MAX as usize // (guaranteed by Rust in this case)
low <= high
low <= (isize::MAX as usize) - 1
low + high <= ((isize::MAX as usize) - 1) + ((isize::MAX as usize) - 1)
((isize::MAX as usize) - 1) + ((isize::MAX as usize) - 1) = usize::MAX - 3
low + high <= usize::MAX - 3
```

The sum of `low + high` provably fits in a `usize::MAX` because `i32` is not zero-sized, so there is no overflow :)

In the second example, it's probably failing because Prusti "forgets" that `len <= isize::MAX as usize` after the first loop iteration without an additional `body_invariant!(len <= isize::MAX as usize)`.

**Comment by fpoli** [comment]
Thanks @Pointerbender! Knowing that, I tried adding the precise range of `len` to the loop invariant of `search2`, but in that function Prusti doesn't seem to recognize that the `a.len()` call returns a `<= isize::MAX as usize` value. I believe this is an incompleteness. We even have additional axioms that encode `.len() * 4 <= isize::MAX as usize` (from #733) but they don't seem to be triggered.

**Comment by fpoli** [comment]
I opened https://github.com/viperproject/prusti-dev/issues/1000

**Comment by fpoli** [comment]
Adding `len == a.len()` seems enough:
```rust
#![allow(dead_code)]
use prusti_contracts::*;

fn search2(a: &[i32], key: i32) -> Option<usize> {
  let len = a.len(); // use len instead of a.len() from now on
  if len == 0 {
    return None 
  }
  let mut low = 0;
  let mut high = len - 1;
  assert!(high < len);
  
  while {
    body_invariant!(high < len && len == a.len());
    low <= high
  } {
    let mid = (low+high) / 2; // no overflow
    let mid_val = a[mid];
    if mid_val < key {
      low = mid + 1;
    } else if mid_val > key {
        if mid == 0 {
            return None
        } else {
            high = mid - 1
        }
    } else {
      return Some(mid);
    }
  }
  None
}
```

**Comment by Pointerbender** [comment]
Today I learned it's also possible to put the `body_invariant!(..)` inside the loop guard instead of in the loop body :) Neat!

**Comment by fpoli** [comment]
We should add it to the user guide. That way, the semantics should be the same as the standard loop invariant of program verification.

**Comment by cmatheja** [comment]
> @cmatheja this is because of #733 : the return value of `<[T]>.len()` is always guaranteed to be at most `isize::MAX` (for non-zero sized `T`) by the Rust type system, because references to allocations larger than `isize::MAX` bytes are forbidden by Rust. 

Thanks for the clarification!

> We should add it to the user guide. That way, the semantics should be the same as the standard loop invariant of program verification.

Agreed. Will do.

**Comment by JonasAlaif** [comment]
> Today I learned it's also possible to put the `body_invariant!(..)` inside the loop guard instead of in the loop body :) Neat!

@Pointerbender this was a thing we figured out when we were thinking about the loop encoding for https://github.com/viperproject/prusti-dev/pull/887. It was a way to essentially force the same encoding as in that PR (if you use `body_invariant!(true)` then you get the loop guard included), except that you then have to write the loop invariant in a different position
